import type { Acessorio, Arma, Compatibilidade } from './tipos';

/* -------------------------------------------------------------------------- *
 * Catálogo de acessórios
 *
 * Os nomes seguem a localização brasileira do jogo — "Boca", "Cano",
 * "Acoplamento Inferior", "Freio Compensado", "Estojo Polimérico". O nome em
 * inglês acompanha cada peça porque boa parte da comunidade joga com o cliente
 * em inglês.
 *
 * Os modificadores foram calibrados a partir das descrições de efeito exibidas
 * no jogo ("reduz o recuo vertical", "aumenta a velocidade do projétil") e de
 * guias da comunidade. O jogo não expõe os multiplicadores exatos, então todo
 * acessório marcado como `curado` mostra aviso de valor aproximado.
 *
 * Sobre recuo, quanto MENOR o valor, melhor: por isso o mod de melhoria usa
 * multiplicador abaixo de 1. O mesmo vale para `adsMs`, `trocaMs` e `recarga`.
 * -------------------------------------------------------------------------- */

const TODAS_DE_FOGO: Compatibilidade = {
  categorias: ['ar', 'carabina', 'smg', 'lmg', 'dmr', 'sniper', 'escopeta', 'pistola'],
};

const LONGAS: Compatibilidade = {
  categorias: ['ar', 'carabina', 'smg', 'lmg', 'dmr', 'sniper'],
};

const LONGAS_E_ESCOPETA: Compatibilidade = {
  categorias: ['ar', 'carabina', 'smg', 'lmg', 'dmr', 'sniper', 'escopeta'],
};

export const ACESSORIOS: Acessorio[] = [
  /* ---------------------------------- Mira ---------------------------------- */
  {
    id: 'mira-ferro',
    nome: 'Alça de Ferro',
    nomeOriginal: 'Iron Sights',
    slot: 'mira',
    custo: 0,
    descricao: 'Mira de fábrica. Não custa pontos e é a que menos atrapalha o manejo.',
    mods: {},
    compat: { ...TODAS_DE_FOGO },
    peca: 'ferro',
    ampliacao: 1,
    procedencia: 'jogo',
  },
  {
    id: 'mira-rmr-100',
    nome: 'R-MR 1.00×',
    nomeOriginal: 'R-MR 1.00x',
    slot: 'mira',
    custo: 6,
    descricao: 'Ponto vermelho miniatura: a mira mais leve, quase sem custo de manejo.',
    mods: { adsMs: { mult: 1.01 }, precisao: { add: 3 } },
    compat: { ...TODAS_DE_FOGO },
    peca: 'ponto-vermelho',
    ampliacao: 1,
    procedencia: 'jogo',
  },
  {
    id: 'mira-osa7-100',
    nome: 'OSA-7 1.00×',
    nomeOriginal: 'OSA-7 1.00x',
    slot: 'mira',
    custo: 8,
    descricao: 'Ponto vermelho de campo amplo, para aquisição e acompanhamento rápidos.',
    mods: { adsMs: { mult: 1.02 }, precisao: { add: 5 } },
    compat: { ...TODAS_DE_FOGO },
    peca: 'ponto-vermelho',
    ampliacao: 1,
    procedencia: 'jogo',
  },
  {
    id: 'mira-holo-100',
    nome: 'HOLO-6 1.00×',
    nomeOriginal: 'HOLO-6 1.00x',
    slot: 'mira',
    custo: 10,
    descricao: 'Holográfica de retículo aberto: leitura limpa mesmo com muita coisa na tela.',
    mods: { adsMs: { mult: 1.03 }, precisao: { add: 6 }, hipfire: { add: 2 } },
    compat: { ...LONGAS },
    peca: 'holografica',
    ampliacao: 1,
    procedencia: 'curado',
  },
  {
    id: 'mira-ros-125',
    nome: 'RO-S 1.25×',
    nomeOriginal: 'RO-S 1.25x',
    slot: 'mira',
    custo: 10,
    descricao: 'Ampliação discreta que ajuda a média distância sem estreitar demais a visão.',
    mods: { adsMs: { mult: 1.04 }, precisao: { add: 8 } },
    compat: { ...LONGAS },
    peca: 'ponto-vermelho',
    ampliacao: 1.25,
    procedencia: 'jogo',
  },
  {
    id: 'mira-rom-175',
    nome: 'RO-M 1.75×',
    nomeOriginal: 'RO-M 1.75x',
    slot: 'mira',
    custo: 12,
    descricao: 'Meio-termo entre ponto vermelho e luneta, útil em mapa aberto.',
    mods: { adsMs: { mult: 1.06 }, precisao: { add: 11 }, mobilidade: { add: -1 } },
    compat: { ...LONGAS },
    peca: 'luneta-media',
    ampliacao: 1.75,
    procedencia: 'jogo',
  },
  {
    id: 'mira-prisim-250',
    nome: 'St Prisim 2.50×',
    nomeOriginal: 'St Prisim 2.50x',
    slot: 'mira',
    custo: 14,
    descricao: 'Luneta prismática com retículo gravado: firme e legível a média distância.',
    mods: { adsMs: { mult: 1.09 }, precisao: { add: 15 }, mobilidade: { add: -2 } },
    compat: { ...LONGAS },
    peca: 'luneta-media',
    ampliacao: 2.5,
    procedencia: 'jogo',
  },
  {
    id: 'mira-tv9-300',
    nome: 'TV-9 3.00×',
    nomeOriginal: 'TV-9 3.00x',
    slot: 'mira',
    custo: 16,
    descricao: 'Ampliação de três vezes, o teto antes de a luneta denunciar o reflexo.',
    mods: { adsMs: { mult: 1.12 }, precisao: { add: 18 }, mobilidade: { add: -3 } },
    compat: { ...LONGAS },
    peca: 'luneta-media',
    ampliacao: 3,
    procedencia: 'curado',
  },
  {
    id: 'mira-ko4-400',
    nome: 'KO-4 4.00×',
    nomeOriginal: 'KO-4 4.00x',
    slot: 'mira',
    custo: 18,
    descricao: 'A partir daqui a lente reflete o sol e entrega sua posição a quem observa.',
    mods: { adsMs: { mult: 1.16 }, precisao: { add: 22 }, mobilidade: { add: -4 } },
    compat: { categorias: ['ar', 'carabina', 'lmg', 'dmr', 'sniper'] },
    peca: 'luneta-longa',
    ampliacao: 4,
    procedencia: 'curado',
  },
  {
    id: 'mira-vdd-600',
    nome: 'VDD 6.00×',
    nomeOriginal: 'VDD 6.00x',
    slot: 'mira',
    custo: 22,
    descricao: 'Luneta de longo alcance com marcações de queda para tiro a distância.',
    mods: { adsMs: { mult: 1.22 }, precisao: { add: 28 }, mobilidade: { add: -6 } },
    compat: { categorias: ['dmr', 'sniper', 'lmg'] },
    peca: 'luneta-longa',
    ampliacao: 6,
    procedencia: 'curado',
  },
  {
    id: 'mira-nx8-800',
    nome: 'NX-8 8.00×',
    nomeOriginal: 'NX-8 8.00x',
    slot: 'mira',
    custo: 26,
    descricao: 'Ampliação máxima: alcança o outro lado do mapa, mas cega o entorno.',
    mods: { adsMs: { mult: 1.3 }, precisao: { add: 34 }, mobilidade: { add: -8 } },
    compat: { categorias: ['sniper'] },
    peca: 'luneta-longa',
    ampliacao: 8,
    procedencia: 'curado',
  },

  /* ---------------------------------- Boca ---------------------------------- */
  {
    id: 'boca-freio-compensado',
    nome: 'Freio Compensado',
    nomeOriginal: 'Compensated Brake',
    slot: 'boca',
    custo: 12,
    descricao: 'Reduz o salto vertical e firma os disparos de acompanhamento.',
    mods: { recuoV: { mult: 0.82 }, controle: { add: 8 }, mobilidade: { add: -1 } },
    compat: { ...LONGAS },
    peca: 'freio',
    procedencia: 'jogo',
  },
  {
    id: 'boca-compensador-linear',
    nome: 'Compensador Linear',
    nomeOriginal: 'Linear Compensator',
    slot: 'boca',
    custo: 10,
    descricao: 'Empurra os gases para frente e domina o desvio horizontal.',
    mods: { recuoH: { mult: 0.76 }, controle: { add: 5 } },
    compat: { ...LONGAS },
    peca: 'compensador',
    procedencia: 'jogo',
  },
  {
    id: 'boca-quebra-chamas',
    nome: 'Quebra-Chamas',
    nomeOriginal: 'Flash Hider',
    slot: 'boca',
    custo: 6,
    descricao: 'Apaga o clarão do disparo, deixando a mira limpa em rajada longa.',
    mods: { recuoV: { mult: 0.94 }, controle: { add: 3 } },
    compat: { ...LONGAS },
    peca: 'quebra-chamas',
    procedencia: 'jogo',
  },
  {
    id: 'boca-supressor-padrao',
    nome: 'Supressor Padrão',
    nomeOriginal: 'Standard Suppressor',
    slot: 'boca',
    custo: 16,
    descricao: 'Some do minimapa inimigo ao atirar; em troca, a bala sai mais devagar.',
    mods: {
      velocidade: { mult: 0.92 },
      alcance: { mult: 0.94 },
      recuoV: { mult: 0.9 },
      adsMs: { mult: 1.04 },
      mobilidade: { add: -3 },
    },
    compat: { ...LONGAS },
    peca: 'supressor',
    procedencia: 'jogo',
  },
  {
    id: 'boca-supressor-cqb',
    nome: 'Supressor CQB',
    nomeOriginal: 'CQB Suppressor',
    slot: 'boca',
    custo: 14,
    descricao: 'Supressor curto: mantém o disfarce sem pesar tanto no manejo.',
    mods: {
      velocidade: { mult: 0.88 },
      alcance: { mult: 0.88 },
      adsMs: { mult: 1.01 },
      hipfire: { add: 4 },
      mobilidade: { add: -1 },
    },
    compat: { categorias: ['smg', 'carabina', 'ar', 'pistola'] },
    peca: 'supressor',
    procedencia: 'jogo',
  },
  {
    id: 'boca-supressor-longo',
    nome: 'Supressor de Longo Alcance',
    nomeOriginal: 'Long Range Suppressor',
    slot: 'boca',
    custo: 20,
    descricao: 'Supressor pesado que preserva a energia do tiro à distância.',
    mods: {
      velocidade: { mult: 1.04 },
      alcance: { mult: 1.02 },
      recuoV: { mult: 0.88 },
      adsMs: { mult: 1.1 },
      mobilidade: { add: -6 },
    },
    compat: { categorias: ['ar', 'lmg', 'dmr', 'sniper'] },
    peca: 'supressor',
    procedencia: 'curado',
  },
  {
    id: 'boca-freio-boca',
    nome: 'Freio de Boca',
    nomeOriginal: 'Muzzle Brake',
    slot: 'boca',
    custo: 12,
    descricao: 'Corta o recuo com força, mas espalha o tiro de quadril.',
    mods: { recuoV: { mult: 0.78 }, recuoH: { mult: 0.88 }, hipfire: { add: -8 } },
    compat: { ...LONGAS },
    peca: 'freio',
    procedencia: 'curado',
  },
  {
    id: 'boca-cone-cqb',
    nome: 'Cone Difusor CQB',
    nomeOriginal: 'CQB Choke',
    slot: 'boca',
    custo: 12,
    descricao: 'Fecha o cone de chumbo e estende o alcance letal da escopeta.',
    mods: { alcance: { mult: 1.25 }, hipfire: { add: -6 } },
    compat: { categorias: ['escopeta'] },
    peca: 'compensador',
    procedencia: 'curado',
  },

  /* ---------------------------------- Cano ---------------------------------- */
  {
    id: 'cano-padrao-180',
    nome: 'Cano Padrão',
    nomeOriginal: 'Standard Barrel',
    slot: 'cano',
    custo: 0,
    descricao: 'Cano de fábrica, sem custo de pontos e sem penalidade.',
    mods: {},
    compat: { ...TODAS_DE_FOGO },
    procedencia: 'jogo',
  },
  {
    id: 'cano-curto-128',
    nome: 'Cano Curto de 128 mm',
    nomeOriginal: '128mm Short Barrel',
    slot: 'cano',
    custo: 10,
    descricao: 'Cano encurtado: mira e movimento muito mais rápidos, alcance sacrificado.',
    mods: {
      adsMs: { mult: 0.9 },
      mobilidade: { add: 6 },
      hipfire: { add: 5 },
      velocidade: { mult: 0.88 },
      alcance: { mult: 0.9 },
      recuoV: { mult: 1.06 },
    },
    compat: { ...LONGAS },
    peca: 'cano-curto',
    procedencia: 'curado',
  },
  {
    id: 'cano-estendido-8',
    nome: 'Cano Estendido de 8″',
    nomeOriginal: '8" Extended Barrel',
    slot: 'cano',
    custo: 14,
    descricao: 'Acelera a bala e empurra os degraus de dano para mais longe.',
    mods: {
      velocidade: { mult: 1.14 },
      alcance: { mult: 1.12 },
      adsMs: { mult: 1.06 },
      mobilidade: { add: -4 },
    },
    compat: { ...LONGAS },
    peca: 'cano-longo',
    procedencia: 'jogo',
  },
  {
    id: 'cano-estriado-409',
    nome: '409 mm Estriado',
    nomeOriginal: '409mm Fluted',
    slot: 'cano',
    custo: 12,
    descricao: 'Cano aliviado por estrias: mais leve, melhora mira e deslocamento mirando.',
    mods: {
      adsMs: { mult: 0.94 },
      mobilidade: { add: 4 },
      velocidade: { mult: 1.04 },
      recuoH: { mult: 1.04 },
    },
    compat: { ...LONGAS },
    peca: 'cano-longo',
    procedencia: 'jogo',
  },
  {
    id: 'cano-pesado-264',
    nome: 'Cano Pesado de 264 mm',
    nomeOriginal: '264mm Heavy Barrel',
    slot: 'cano',
    custo: 16,
    descricao: 'Massa extra na frente: o cano sobe menos e o tiro agrupa melhor.',
    mods: {
      recuoV: { mult: 0.86 },
      recuoH: { mult: 0.9 },
      precisao: { add: 8 },
      velocidade: { mult: 1.06 },
      adsMs: { mult: 1.1 },
      mobilidade: { add: -7 },
    },
    compat: { ...LONGAS },
    peca: 'cano-pesado',
    procedencia: 'curado',
  },
  {
    id: 'cano-prototipo-264',
    nome: 'Cano Protótipo de 264 mm',
    nomeOriginal: '264mm Prototype Barrel',
    slot: 'cano',
    custo: 18,
    descricao: 'Cano experimental com a maior velocidade de saída disponível.',
    mods: {
      velocidade: { mult: 1.22 },
      alcance: { mult: 1.16 },
      adsMs: { mult: 1.12 },
      mobilidade: { add: -8 },
      controle: { add: -3 },
    },
    compat: { categorias: ['ar', 'carabina', 'lmg', 'dmr', 'sniper'] },
    peca: 'cano-pesado',
    procedencia: 'jogo',
  },
  {
    id: 'cano-escopeta-curto',
    nome: 'Cano Serrado',
    nomeOriginal: 'Sawed-Off Barrel',
    slot: 'cano',
    custo: 10,
    descricao: 'Espalha o chumbo e deixa a escopeta ágil dentro de casa.',
    mods: { alcance: { mult: 0.78 }, adsMs: { mult: 0.88 }, mobilidade: { add: 8 }, hipfire: { add: 8 } },
    compat: { categorias: ['escopeta'] },
    peca: 'cano-curto',
    procedencia: 'curado',
  },
  {
    id: 'cano-escopeta-longo',
    nome: 'Cano Longo de Escopeta',
    nomeOriginal: 'Long Shotgun Barrel',
    slot: 'cano',
    custo: 13,
    descricao: 'Fecha o cone de chumbo e estica o alcance letal do disparo.',
    mods: { alcance: { mult: 1.3 }, velocidade: { mult: 1.08 }, adsMs: { mult: 1.1 }, mobilidade: { add: -6 } },
    compat: { categorias: ['escopeta'] },
    peca: 'cano-longo',
    procedencia: 'curado',
  },
  {
    id: 'cano-pistola-estendido',
    nome: 'Cano de Pistola Estendido',
    nomeOriginal: 'Extended Pistol Barrel',
    slot: 'cano',
    custo: 10,
    descricao: 'Ganha velocidade e alcance sem comprometer muito o saque.',
    mods: { velocidade: { mult: 1.15 }, alcance: { mult: 1.12 }, adsMs: { mult: 1.05 }, mobilidade: { add: -3 } },
    compat: { categorias: ['pistola'] },
    peca: 'cano-longo',
    procedencia: 'curado',
  },
  {
    id: 'cano-pistola-compensado',
    nome: 'Cano Compensado de Pistola',
    nomeOriginal: 'Ported Pistol Barrel',
    slot: 'cano',
    custo: 9,
    descricao: 'Furos de alívio no cano derrubam o salto entre um tiro e outro.',
    mods: { recuoV: { mult: 0.85 }, controle: { add: 6 }, velocidade: { mult: 0.96 } },
    compat: { categorias: ['pistola'] },
    peca: 'cano-curto',
    procedencia: 'curado',
  },

  /* --------------------------- Acoplamento Inferior --------------------------- */
  {
    id: 'acopl-vertical-classica',
    nome: 'Empunhadura Vertical Clássica',
    nomeOriginal: 'Classic Vertical',
    slot: 'acoplamento',
    custo: 10,
    descricao: 'O maior controle de recuo vertical do slot.',
    mods: { recuoV: { mult: 0.84 }, controle: { add: 7 }, mobilidade: { add: -2 } },
    compat: { ...LONGAS_E_ESCOPETA },
    peca: 'empunhadura-vertical',
    procedencia: 'jogo',
  },
  {
    id: 'acopl-angular',
    nome: 'Empunhadura Angular',
    nomeOriginal: 'Angled Grip',
    slot: 'acoplamento',
    custo: 9,
    descricao: 'Acelera a subida da arma para a mira e segura o desvio lateral.',
    mods: { adsMs: { mult: 0.94 }, recuoH: { mult: 0.88 }, controle: { add: 3 } },
    compat: { ...LONGAS },
    peca: 'empunhadura-angular',
    procedencia: 'jogo',
  },
  {
    id: 'acopl-apoio-mao',
    nome: 'Apoio de Mão',
    nomeOriginal: 'Handstop',
    slot: 'acoplamento',
    custo: 7,
    descricao: 'Peça leve que melhora o tiro de quadril e o deslocamento.',
    mods: { hipfire: { add: 8 }, mobilidade: { add: 4 }, recuoV: { mult: 0.96 } },
    compat: { ...LONGAS_E_ESCOPETA },
    peca: 'apoio-mao',
    procedencia: 'jogo',
  },
  {
    id: 'acopl-bipe',
    nome: 'Bipé',
    nomeOriginal: 'Bipod',
    slot: 'acoplamento',
    custo: 12,
    descricao: 'Apoiado em cobertura, praticamente zera o recuo — de pé, atrapalha.',
    mods: { recuoV: { mult: 0.7 }, recuoH: { mult: 0.7 }, mobilidade: { add: -6 }, adsMs: { mult: 1.05 } },
    compat: { categorias: ['lmg', 'dmr', 'sniper', 'ar'] },
    peca: 'bipe',
    procedencia: 'jogo',
  },
  {
    id: 'acopl-empunhadura-leve',
    nome: 'Empunhadura Leve',
    nomeOriginal: 'Lightweight Grip',
    slot: 'acoplamento',
    custo: 6,
    descricao: 'Troca estabilidade por velocidade de manejo.',
    mods: { adsMs: { mult: 0.92 }, mobilidade: { add: 5 }, recuoH: { mult: 1.05 } },
    compat: { ...LONGAS_E_ESCOPETA },
    peca: 'apoio-mao',
    procedencia: 'curado',
  },

  /* ------------------------------- Carregador ------------------------------- */
  {
    id: 'carreg-padrao',
    nome: 'Carregador Padrão',
    nomeOriginal: 'Standard Magazine',
    slot: 'carregador',
    custo: 0,
    descricao: 'Capacidade de fábrica, sem custo.',
    mods: {},
    compat: { ...TODAS_DE_FOGO },
    procedencia: 'jogo',
  },
  {
    id: 'carreg-rapido',
    nome: 'Carregador de Saque Rápido',
    nomeOriginal: 'Fast Magazine',
    slot: 'carregador',
    custo: 8,
    descricao: 'Mesma capacidade, recarga bem mais rápida.',
    mods: { recarga: { mult: 0.82 } },
    compat: { ...TODAS_DE_FOGO },
    peca: 'carregador-curto',
    procedencia: 'jogo',
  },
  {
    id: 'carreg-estendido',
    nome: 'Carregador Estendido',
    nomeOriginal: 'Extended Magazine',
    slot: 'carregador',
    custo: 12,
    descricao: 'Metade de munição a mais no pente, ao custo de recarga e peso.',
    mods: { carregador: { mult: 1.5 }, recarga: { mult: 1.12 }, mobilidade: { add: -3 } },
    compat: { categorias: ['ar', 'carabina', 'smg', 'dmr', 'pistola'] },
    peca: 'carregador-longo',
    procedencia: 'jogo',
  },
  {
    id: 'carreg-reduzido',
    nome: 'Carregador Reduzido',
    nomeOriginal: 'Short Magazine',
    slot: 'carregador',
    custo: 4,
    descricao: 'Menos tiros, porém arma mais leve e recarga curta.',
    mods: { carregador: { mult: 0.7 }, recarga: { mult: 0.86 }, mobilidade: { add: 4 }, adsMs: { mult: 0.97 } },
    compat: { categorias: ['ar', 'carabina', 'smg', 'lmg', 'dmr'] },
    peca: 'carregador-curto',
    procedencia: 'curado',
  },
  {
    id: 'carreg-tambor',
    nome: 'Tambor',
    nomeOriginal: 'Drum Magazine',
    slot: 'carregador',
    custo: 18,
    descricao: 'Muita munição sem parar de atirar — e um peso considerável.',
    mods: { carregador: { mult: 2.2 }, recarga: { mult: 1.4 }, mobilidade: { add: -9 }, adsMs: { mult: 1.06 } },
    compat: { categorias: ['ar', 'carabina', 'smg', 'lmg'] },
    peca: 'tambor',
    procedencia: 'jogo',
  },

  /* --------------------------------- Munição --------------------------------- */
  {
    id: 'mun-padrao',
    nome: 'Munição Padrão',
    nomeOriginal: 'Standard Ammunition',
    slot: 'municao',
    custo: 0,
    descricao: 'Cartucho de fábrica, equilibrado em tudo.',
    mods: {},
    compat: { ...TODAS_DE_FOGO },
    procedencia: 'jogo',
  },
  {
    id: 'mun-polimero',
    nome: 'Estojo Polimérico',
    nomeOriginal: 'Polymer Case',
    slot: 'municao',
    custo: 8,
    descricao: 'Cartucho leve: acelera a mira e o deslocamento, com bala mais lenta.',
    mods: { mobilidade: { add: 5 }, adsMs: { mult: 0.95 }, velocidade: { mult: 0.94 }, recarga: { mult: 0.95 } },
    compat: { ...LONGAS },
    procedencia: 'jogo',
  },
  {
    id: 'mun-ponta-oca',
    nome: 'Ponta Oca',
    nomeOriginal: 'Hollow Point',
    slot: 'municao',
    custo: 14,
    descricao: 'Mais dano no vão curto; a energia se esgota rápido na distância.',
    mods: { dano: { mult: 1.1 }, alcance: { mult: 0.8 }, velocidade: { mult: 0.96 } },
    compat: { categorias: ['ar', 'carabina', 'smg', 'lmg', 'pistola', 'escopeta'] },
    procedencia: 'curado',
  },
  {
    id: 'mun-ponta-macia',
    nome: 'Ponta Macia',
    nomeOriginal: 'Soft Point',
    slot: 'municao',
    custo: 12,
    descricao: 'Ganho moderado de dano com perda contida de alcance.',
    mods: { dano: { mult: 1.05 }, alcance: { mult: 0.9 } },
    compat: { ...LONGAS },
    procedencia: 'curado',
  },
  {
    id: 'mun-encamisada',
    nome: 'Munição Encamisada',
    nomeOriginal: 'Full Metal Jacket',
    slot: 'municao',
    custo: 10,
    descricao: 'Atravessa material fino e mantém o dano por mais tempo.',
    mods: { alcance: { mult: 1.15 }, velocidade: { mult: 1.05 }, dano: { mult: 0.98 } },
    compat: { ...LONGAS },
    procedencia: 'jogo',
  },
  {
    id: 'mun-perfurante',
    nome: 'Munição Perfurante',
    nomeOriginal: 'Armor Piercing',
    slot: 'municao',
    custo: 15,
    descricao: 'Perfura blindagem leve e sustenta o dano contra alvos protegidos.',
    mods: { alcance: { mult: 1.2 }, velocidade: { mult: 1.1 }, dano: { mult: 0.96 }, recuoV: { mult: 1.05 } },
    compat: { categorias: ['ar', 'lmg', 'dmr', 'sniper', 'carabina'] },
    procedencia: 'curado',
  },
  {
    id: 'mun-subsonica',
    nome: 'Munição Subsônica',
    nomeOriginal: 'Subsonic Ammunition',
    slot: 'municao',
    custo: 12,
    descricao: 'Tiro abafado e sem estampido supersônico — a bala fica bem mais lenta.',
    mods: { velocidade: { mult: 0.7 }, alcance: { mult: 0.85 }, recuoV: { mult: 0.9 } },
    compat: { categorias: ['ar', 'carabina', 'smg', 'dmr', 'sniper', 'pistola'] },
    procedencia: 'curado',
  },
  {
    id: 'mun-tracante-pesada',
    nome: 'Traçante Pesada',
    nomeOriginal: 'Heavy Tracer',
    slot: 'municao',
    custo: 10,
    descricao: 'Projétil pesado e veloz; o rastro luminoso denuncia sua posição.',
    mods: { velocidade: { mult: 1.12 }, alcance: { mult: 1.06 }, recuoV: { mult: 1.08 } },
    compat: { ...LONGAS },
    procedencia: 'curado',
  },

  /* -------------------------------- Ergonomia -------------------------------- */
  {
    id: 'ergo-coronha-padrao',
    nome: 'Coronha Padrão',
    nomeOriginal: 'Standard Stock',
    slot: 'ergonomia',
    custo: 0,
    descricao: 'Coronha de fábrica, sem custo.',
    mods: {},
    compat: { ...LONGAS_E_ESCOPETA },
    procedencia: 'jogo',
  },
  {
    id: 'ergo-coronha-leve',
    nome: 'Coronha Leve',
    nomeOriginal: 'Lightweight Stock',
    slot: 'ergonomia',
    custo: 9,
    descricao: 'Estrutura vazada: mira e corrida mais rápidas, arma mais nervosa.',
    mods: { adsMs: { mult: 0.9 }, mobilidade: { add: 7 }, trocaMs: { mult: 0.92 }, recuoV: { mult: 1.08 } },
    compat: { ...LONGAS_E_ESCOPETA },
    peca: 'coronha-leve',
    procedencia: 'jogo',
  },
  {
    id: 'ergo-coronha-pesada',
    nome: 'Coronha Pesada',
    nomeOriginal: 'Heavy Stock',
    slot: 'ergonomia',
    custo: 11,
    descricao: 'Absorve o coice no ombro e agrupa a rajada, ao custo de agilidade.',
    mods: { recuoV: { mult: 0.85 }, recuoH: { mult: 0.9 }, precisao: { add: 6 }, mobilidade: { add: -6 }, adsMs: { mult: 1.07 } },
    compat: { ...LONGAS_E_ESCOPETA },
    peca: 'coronha-pesada',
    procedencia: 'jogo',
  },
  {
    id: 'ergo-coronha-retratil',
    nome: 'Coronha Retrátil',
    nomeOriginal: 'Collapsible Stock',
    slot: 'ergonomia',
    custo: 8,
    descricao: 'Ajustável: bom equilíbrio entre estabilidade e velocidade de manejo.',
    mods: { adsMs: { mult: 0.95 }, mobilidade: { add: 3 }, recuoH: { mult: 0.96 } },
    compat: { ...LONGAS },
    peca: 'coronha-leve',
    procedencia: 'curado',
  },
  {
    id: 'ergo-empunhadura-emborrachada',
    nome: 'Empunhadura Emborrachada',
    nomeOriginal: 'Rubberized Grip',
    slot: 'ergonomia',
    custo: 7,
    descricao: 'Punho aderente que firma a arma no primeiro tiro.',
    mods: { controle: { add: 6 }, recuoV: { mult: 0.93 } },
    compat: { ...TODAS_DE_FOGO },
    procedencia: 'curado',
  },
  {
    id: 'ergo-ferrolho-leve',
    nome: 'Ferrolho Leve',
    nomeOriginal: 'Lightweight Bolt',
    slot: 'ergonomia',
    custo: 13,
    descricao: 'Acelera o ciclo do ferrolho entre um tiro e o próximo.',
    mods: { rpm: { mult: 1.18 }, precisao: { add: -3 } },
    compat: { categorias: ['sniper'] },
    procedencia: 'curado',
  },

  /* ---------------------------- Acessório Óptico ---------------------------- */
  {
    id: 'opt-ampliador-200',
    nome: 'Ampliador 2.00×',
    nomeOriginal: '2.00x Magnifier',
    slot: 'opticoExtra',
    custo: 12,
    descricao: 'Basculante: dobra a ampliação da mira quando você precisa e sai do caminho depois.',
    mods: { adsMs: { mult: 1.05 }, precisao: { add: 9 }, mobilidade: { add: -2 } },
    compat: { ...LONGAS },
    peca: 'ampliador',
    procedencia: 'jogo',
  },
  {
    id: 'opt-reticulo-iluminado',
    nome: 'Retículo Iluminado',
    nomeOriginal: 'Illuminated Reticle',
    slot: 'opticoExtra',
    custo: 6,
    descricao: 'Retículo aceso: leitura instantânea em interior escuro e contraluz.',
    mods: { precisao: { add: 3 }, adsMs: { mult: 0.99 } },
    compat: { ...LONGAS },
    procedencia: 'curado',
  },
  {
    id: 'opt-filtro-antirreflexo',
    nome: 'Filtro Antirreflexo',
    nomeOriginal: 'Anti-Glare Filter',
    slot: 'opticoExtra',
    custo: 10,
    descricao: 'Elimina o brilho da lente que denuncia snipers a distância.',
    mods: { precisao: { add: 2 }, adsMs: { mult: 1.02 } },
    compat: { categorias: ['dmr', 'sniper', 'ar', 'lmg'] },
    procedencia: 'curado',
  },
  {
    id: 'opt-mira-auxiliar-45',
    nome: 'Mira Auxiliar 45°',
    nomeOriginal: '45° Offset Sight',
    slot: 'opticoExtra',
    custo: 11,
    descricao: 'Ponto vermelho inclinado: gire a arma e resolva o alvo colado.',
    mods: { adsMs: { mult: 1.03 }, hipfire: { add: 6 } },
    compat: { categorias: ['ar', 'carabina', 'dmr', 'sniper', 'lmg'] },
    procedencia: 'curado',
  },

  /* --------------------------- Acessório Esquerdo --------------------------- */
  {
    id: 'esq-laser-azul-120',
    nome: 'Laser Azul 120MW',
    nomeOriginal: '120MW Blue Laser',
    slot: 'lateralEsquerda',
    custo: 8,
    descricao: 'Aperta o cone do tiro de quadril; o feixe é visível para o inimigo.',
    mods: { hipfire: { add: 12 } },
    compat: { ...TODAS_DE_FOGO },
    peca: 'laser',
    procedencia: 'jogo',
  },
  {
    id: 'esq-laser-verde-180',
    nome: 'Laser Verde 180MW',
    nomeOriginal: '180MW Green Laser',
    slot: 'lateralEsquerda',
    custo: 11,
    descricao: 'Feixe mais forte: o melhor tiro de quadril, e o mais fácil de rastrear.',
    mods: { hipfire: { add: 18 }, mobilidade: { add: -1 } },
    compat: { ...TODAS_DE_FOGO },
    peca: 'laser',
    procedencia: 'curado',
  },
  {
    id: 'esq-lanterna',
    nome: 'Lanterna Tática',
    nomeOriginal: 'Tactical Flashlight',
    slot: 'lateralEsquerda',
    custo: 7,
    descricao: 'Ofusca quem está à frente em ambiente fechado — e entrega você no escuro.',
    mods: { hipfire: { add: 5 } },
    compat: { ...TODAS_DE_FOGO },
    peca: 'lanterna',
    procedencia: 'jogo',
  },
  {
    id: 'esq-designador-iv',
    nome: 'Designador Infravermelho',
    nomeOriginal: 'IR Designator',
    slot: 'lateralEsquerda',
    custo: 10,
    descricao: 'Feixe invisível a olho nu, visível apenas por visão noturna.',
    mods: { hipfire: { add: 9 } },
    compat: { ...LONGAS },
    peca: 'laser',
    procedencia: 'curado',
  },

  /* ---------------------------- Acessório Direito ---------------------------- */
  {
    id: 'dir-saque-rapido',
    nome: 'Empunhadura de Saque Rápido',
    nomeOriginal: 'Quick Draw Grip',
    slot: 'lateralDireita',
    custo: 9,
    descricao: 'Acelera tirar a arma das costas e alternar entre primária e secundária.',
    mods: { trocaMs: { mult: 0.82 }, adsMs: { mult: 0.97 } },
    compat: { ...TODAS_DE_FOGO },
    procedencia: 'curado',
  },
  {
    id: 'dir-apoio-bochecha',
    nome: 'Apoio de Bochecha',
    nomeOriginal: 'Cheek Rest',
    slot: 'lateralDireita',
    custo: 7,
    descricao: 'Alinha o olho à mira e reduz a oscilação ao segurar a respiração.',
    mods: { precisao: { add: 7 }, adsMs: { mult: 1.02 } },
    compat: { categorias: ['ar', 'carabina', 'lmg', 'dmr', 'sniper'] },
    procedencia: 'curado',
  },
  {
    id: 'dir-contrapeso',
    nome: 'Contrapeso',
    nomeOriginal: 'Counterweight',
    slot: 'lateralDireita',
    custo: 9,
    descricao: 'Peso lateral que corta o desvio horizontal da rajada.',
    mods: { recuoH: { mult: 0.82 }, mobilidade: { add: -3 } },
    compat: { ...LONGAS },
    procedencia: 'curado',
  },
  {
    id: 'dir-fita-manejo',
    nome: 'Fita de Manejo',
    nomeOriginal: 'Grip Tape',
    slot: 'lateralDireita',
    custo: 6,
    descricao: 'Aderência simples e barata para subir a arma à mira mais rápido.',
    mods: { adsMs: { mult: 0.95 } },
    compat: { ...TODAS_DE_FOGO },
    procedencia: 'curado',
  },
];

export const ACESSORIOS_POR_ID = new Map<string, Acessorio>(ACESSORIOS.map((a) => [a.id, a]));

/** Decide se um acessório pode ser montado em determinada arma. */
export function ehCompativel(acessorio: Acessorio, arma: Arma): boolean {
  if (!arma.slots.includes(acessorio.slot)) return false;

  const { armas, exceto, categorias, arquetipos } = acessorio.compat;
  if (exceto?.includes(arma.id)) return false;
  if (armas) return armas.includes(arma.id);

  const porCategoria = categorias ? categorias.includes(arma.categoria) : false;
  const porArquetipo = arquetipos ? arquetipos.includes(arma.arquetipo) : false;
  if (!categorias && !arquetipos) return true;
  return porCategoria || porArquetipo;
}

/** Acessórios compatíveis com uma arma, agrupados pelo slot. */
export function acessoriosDaArma(arma: Arma): Map<string, Acessorio[]> {
  const mapa = new Map<string, Acessorio[]>();
  for (const slot of arma.slots) {
    const lista = ACESSORIOS.filter((a) => a.slot === slot && ehCompativel(a, arma));
    if (lista.length > 0) mapa.set(slot, lista);
  }
  return mapa;
}
