import type { Arma, ArquetipoArma, CategoriaArma, DegrauDano, IdClasse, IdSlot } from './tipos';

/* -------------------------------------------------------------------------- *
 * Procedência dos números
 *
 * Cadência, velocidade de projétil, capacidade, recarga e tempo de mira vêm de
 * levantamentos da comunidade sobre o jogo. As escadas de dano seguem o padrão
 * do Battlefield 6, em que cada degrau é 100 dividido por um número inteiro de
 * tiros — o que permite reconstruir o perfil a partir do "tiros para matar" por
 * distância. Onde não havia medição publicada, o degrau foi derivado de uma arma
 * de mesmo calibre e cadência, e a arma fica marcada como `curado`.
 * -------------------------------------------------------------------------- */

const SLOTS_COMPLETOS: IdSlot[] = [
  'mira',
  'boca',
  'cano',
  'acoplamento',
  'carregador',
  'municao',
  'ergonomia',
  'opticoExtra',
  'lateralEsquerda',
  'lateralDireita',
];

const SLOTS_ESCOPETA: IdSlot[] = [
  'mira',
  'boca',
  'cano',
  'acoplamento',
  'carregador',
  'municao',
  'ergonomia',
  'lateralEsquerda',
  'lateralDireita',
];

const SLOTS_PISTOLA: IdSlot[] = [
  'mira',
  'boca',
  'cano',
  'carregador',
  'municao',
  'lateralEsquerda',
  'lateralDireita',
];

const CLASSE_DA_CATEGORIA: Record<CategoriaArma, IdClasse | null> = {
  ar: 'assalto',
  lmg: 'suporte',
  carabina: 'engenheiro',
  sniper: 'reconhecimento',
  dmr: 'reconhecimento',
  smg: null,
  escopeta: null,
  pistola: null,
  'corpo-a-corpo': null,
};

function slotsDaCategoria(categoria: CategoriaArma): IdSlot[] {
  if (categoria === 'corpo-a-corpo') return [];
  if (categoria === 'pistola') return SLOTS_PISTOLA;
  if (categoria === 'escopeta') return SLOTS_ESCOPETA;
  return SLOTS_COMPLETOS;
}

type EntradaArma = Omit<
  Arma,
  'classeAssinatura' | 'slots' | 'projeteis' | 'arrasto' | 'temporada' | 'dano'
> & {
  dano: [number, number][];
  projeteis?: number;
  arrasto?: number;
  temporada?: number;
  slots?: IdSlot[];
};

function montar(entrada: EntradaArma): Arma {
  const dano: DegrauDano[] = entrada.dano.map(([d, distancia]) => ({ dano: d, distancia }));
  return {
    ...entrada,
    dano,
    projeteis: entrada.projeteis ?? 1,
    arrasto: entrada.arrasto ?? 1,
    temporada: entrada.temporada ?? 0,
    classeAssinatura: CLASSE_DA_CATEGORIA[entrada.categoria],
    slots: entrada.slots ?? slotsDaCategoria(entrada.categoria),
  };
}

/* ------------------------------- Fuzis de assalto ------------------------------- */

const FUZIS: EntradaArma[] = [
  {
    id: 'ak4d',
    nome: 'AK4D',
    categoria: 'ar',
    arquetipo: 'ar-leste',
    resumo: 'Fuzil pesado de 7,62 mm: três tiros derrubam, mas o coice cobra pulso firme.',
    dano: [
      [33.4, 0],
      [25, 21],
      [20, 75],
    ],
    rpm: 514,
    velocidade: 720,
    arrasto: 1.05,
    headshot: 1.35,
    carregador: 20,
    recarga: 3.3,
    recargaVazia: 4.1,
    adsMs: 350,
    trocaMs: 620,
    precisao: 27,
    controle: 35,
    mobilidade: 52,
    hipfire: 40,
    recuoV: 0.72,
    recuoH: 0.38,
    disparo: ['automatico', 'semiautomatico'],
    procedencia: 'jogo',
  },
  {
    id: 'tr-7',
    nome: 'TR-7',
    categoria: 'ar',
    arquetipo: 'ar-otan',
    resumo: 'Mesmo soco de 7,62 mm do AK4D com cadência bem maior — o preço é o recuo horizontal.',
    dano: [
      [33.4, 0],
      [25, 21],
      [20, 75],
    ],
    rpm: 720,
    velocidade: 648,
    arrasto: 1.05,
    headshot: 1.35,
    carregador: 20,
    recarga: 3.3,
    recargaVazia: 4.05,
    adsMs: 340,
    trocaMs: 600,
    precisao: 17,
    controle: 29,
    mobilidade: 52,
    hipfire: 40,
    recuoV: 0.78,
    recuoH: 0.44,
    disparo: ['automatico', 'rajada'],
    procedencia: 'jogo',
  },
  {
    id: 'sor-556-mk2',
    nome: 'SOR-556 Mk2',
    categoria: 'ar',
    arquetipo: 'ar-otan',
    resumo: 'Cadência baixa e recuo previsível: o fuzil mais fácil de controlar do arsenal.',
    dano: [
      [25, 0],
      [20, 21],
      [16.7, 75],
    ],
    rpm: 568,
    velocidade: 800,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.67,
    recargaVazia: 3.4,
    adsMs: 320,
    trocaMs: 560,
    precisao: 45,
    controle: 48,
    mobilidade: 52,
    hipfire: 40,
    recuoV: 0.52,
    recuoH: 0.24,
    disparo: ['automatico', 'rajada', 'semiautomatico'],
    procedencia: 'jogo',
  },
  {
    id: 'b36a4',
    nome: 'B36A4',
    categoria: 'ar',
    arquetipo: 'bullpup',
    resumo: 'Bullpup equilibrado: compacto para o vão interno, estável o bastante para média distância.',
    dano: [
      [25, 0],
      [20, 35],
    ],
    rpm: 720,
    velocidade: 780,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.75,
    recargaVazia: 3.5,
    adsMs: 330,
    trocaMs: 580,
    precisao: 42,
    controle: 44,
    mobilidade: 54,
    hipfire: 42,
    recuoV: 0.56,
    recuoH: 0.28,
    disparo: ['automatico', 'rajada'],
    procedencia: 'curado',
  },
  {
    id: 'l85a3',
    nome: 'L85A3',
    categoria: 'ar',
    arquetipo: 'bullpup',
    resumo: 'Bullpup de cadência contida e a maior velocidade de bala entre os fuzis.',
    dano: [
      [25, 0],
      [20, 35],
    ],
    rpm: 635,
    velocidade: 814,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.85,
    recargaVazia: 3.6,
    adsMs: 335,
    trocaMs: 590,
    precisao: 48,
    controle: 46,
    mobilidade: 50,
    hipfire: 38,
    recuoV: 0.5,
    recuoH: 0.26,
    disparo: ['automatico', 'semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'm433',
    nome: 'M433',
    categoria: 'ar',
    arquetipo: 'ar-otan',
    resumo: 'Cadência alta de 5,56 mm — vence a troca de tiro no vão curto se o primeiro pente acertar.',
    dano: [
      [25, 0],
      [20, 21],
      [16.7, 75],
    ],
    rpm: 830,
    velocidade: 670,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.6,
    recargaVazia: 3.35,
    adsMs: 315,
    trocaMs: 555,
    precisao: 34,
    controle: 38,
    mobilidade: 55,
    hipfire: 43,
    recuoV: 0.62,
    recuoH: 0.34,
    disparo: ['automatico', 'rajada'],
    procedencia: 'curado',
  },
  {
    id: 'kord-6p67',
    nome: 'KORD 6P67',
    categoria: 'ar',
    arquetipo: 'ar-leste',
    resumo: '900 disparos por minuto: o fuzil mais rápido do jogo, com dano por tiro modesto.',
    dano: [
      [20, 0],
      [16.7, 35],
    ],
    rpm: 900,
    velocidade: 760,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.7,
    recargaVazia: 3.45,
    adsMs: 325,
    trocaMs: 570,
    precisao: 30,
    controle: 40,
    mobilidade: 54,
    hipfire: 44,
    recuoV: 0.58,
    recuoH: 0.36,
    disparo: ['automatico', 'rajada'],
    procedencia: 'curado',
  },
  {
    id: 'nvo-228e',
    nome: 'NVO-228E',
    categoria: 'ar',
    arquetipo: 'ar-leste',
    resumo: 'Perfil híbrido: soco de três tiros no vão curto que degrada em degraus suaves.',
    dano: [
      [33.4, 0],
      [27.3, 9],
      [21.5, 21],
      [20, 36],
      [16.7, 75],
    ],
    rpm: 654,
    velocidade: 671,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.8,
    recargaVazia: 3.55,
    adsMs: 340,
    trocaMs: 585,
    precisao: 38,
    controle: 41,
    mobilidade: 51,
    hipfire: 40,
    recuoV: 0.6,
    recuoH: 0.3,
    disparo: ['automatico', 'semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'ef88',
    nome: 'EF88',
    categoria: 'ar',
    arquetipo: 'bullpup',
    resumo: 'Bullpup australiano da Temporada 4: mira rápida e recuo curto e vertical.',
    dano: [
      [25, 0],
      [20, 30],
      [16.7, 75],
    ],
    rpm: 700,
    velocidade: 790,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.7,
    recargaVazia: 3.45,
    adsMs: 310,
    trocaMs: 545,
    precisao: 46,
    controle: 45,
    mobilidade: 56,
    hipfire: 42,
    recuoV: 0.54,
    recuoH: 0.22,
    disparo: ['automatico', 'rajada', 'semiautomatico'],
    temporada: 4,
    procedencia: 'curado',
  },
  {
    id: 'vcr-2',
    nome: 'VCR-2',
    categoria: 'ar',
    arquetipo: 'bullpup',
    resumo: 'Bullpup experimental da Temporada 2: cadência alta em um corpo muito curto.',
    dano: [
      [25, 0],
      [20, 30],
      [16.7, 75],
    ],
    rpm: 780,
    velocidade: 750,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.65,
    recargaVazia: 3.4,
    adsMs: 320,
    trocaMs: 560,
    precisao: 40,
    controle: 43,
    mobilidade: 57,
    hipfire: 44,
    recuoV: 0.58,
    recuoH: 0.3,
    disparo: ['automatico', 'rajada'],
    temporada: 2,
    procedencia: 'curado',
  },
  {
    id: 'm16a4',
    nome: 'M16A4',
    categoria: 'ar',
    arquetipo: 'ar-otan',
    resumo: 'Rajada de três da Temporada 3: letal a distância nas mãos de quem acerta o pente.',
    dano: [
      [25, 0],
      [20, 25],
      [16.7, 80],
    ],
    rpm: 800,
    velocidade: 900,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.72,
    recargaVazia: 3.5,
    adsMs: 330,
    trocaMs: 575,
    precisao: 52,
    controle: 40,
    mobilidade: 50,
    hipfire: 38,
    recuoV: 0.64,
    recuoH: 0.2,
    disparo: ['rajada', 'semiautomatico'],
    temporada: 3,
    procedencia: 'curado',
  },
];

/* --------------------------------- Carabinas --------------------------------- */

const CARABINAS: EntradaArma[] = [
  {
    id: 'm4a1',
    nome: 'M4A1',
    categoria: 'carabina',
    arquetipo: 'carabina-curta',
    resumo: 'A carabina de referência: 900 RPM, manejo leve e recuo que sobe reto.',
    dano: [
      [25, 0],
      [21.5, 9],
      [17.7, 21],
      [16.7, 36],
      [14.3, 75],
    ],
    rpm: 900,
    velocidade: 630,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.5,
    recargaVazia: 3.2,
    adsMs: 280,
    trocaMs: 520,
    precisao: 36,
    controle: 42,
    mobilidade: 62,
    hipfire: 47,
    recuoV: 0.56,
    recuoH: 0.26,
    disparo: ['automatico', 'rajada', 'semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'ak-205',
    nome: 'AK-205',
    categoria: 'carabina',
    arquetipo: 'ar-leste',
    resumo: 'Dano plano e a maior velocidade de bala da categoria: castiga a média distância.',
    dano: [
      [20, 0],
      [17.7, 9],
      [15, 21],
      [14.3, 36],
      [12.5, 75],
    ],
    rpm: 720,
    velocidade: 737,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.8,
    recargaVazia: 3.5,
    adsMs: 310,
    trocaMs: 545,
    precisao: 88,
    controle: 64,
    mobilidade: 56,
    hipfire: 47,
    recuoV: 0.44,
    recuoH: 0.2,
    disparo: ['automatico', 'semiautomatico'],
    procedencia: 'jogo',
  },
  {
    id: 'm417-a2',
    nome: 'M417 A2',
    categoria: 'carabina',
    arquetipo: 'carabina-curta',
    resumo: 'Carabina de 7,62 mm: derruba em três tiros de perto e segura bem até média distância.',
    dano: [
      [33.4, 0],
      [27.3, 9],
      [21.5, 21],
      [20, 36],
      [16.7, 75],
    ],
    rpm: 654,
    velocidade: 600,
    arrasto: 1.05,
    headshot: 1.35,
    carregador: 20,
    recarga: 2.57,
    recargaVazia: 3.3,
    adsMs: 350,
    trocaMs: 575,
    precisao: 28,
    controle: 30,
    mobilidade: 60,
    hipfire: 47,
    recuoV: 0.74,
    recuoH: 0.36,
    disparo: ['automatico', 'semiautomatico'],
    procedencia: 'jogo',
  },
  {
    id: 'grt-bc',
    nome: 'GRT-BC',
    categoria: 'carabina',
    arquetipo: 'carabina-curta',
    resumo: 'Cadência alta com carregador cheio: pensada para limpar cômodo atrás de cômodo.',
    dano: [
      [25, 0],
      [21.5, 9],
      [17.7, 21],
      [16.7, 36],
      [14.3, 75],
    ],
    rpm: 830,
    velocidade: 599,
    headshot: 1.35,
    carregador: 30,
    recarga: 3.35,
    recargaVazia: 4.05,
    adsMs: 280,
    trocaMs: 520,
    precisao: 28,
    controle: 37,
    mobilidade: 64,
    hipfire: 47,
    recuoV: 0.64,
    recuoH: 0.34,
    disparo: ['automatico', 'rajada'],
    procedencia: 'jogo',
  },
  {
    id: 'qbz-192',
    nome: 'QBZ-192',
    categoria: 'carabina',
    arquetipo: 'bullpup',
    resumo: 'Bullpup compacta com boa velocidade de bala para o tamanho.',
    dano: [
      [25, 0],
      [21.5, 9],
      [17.7, 21],
      [16.7, 36],
      [14.3, 75],
    ],
    rpm: 771,
    velocidade: 644,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.9,
    recargaVazia: 3.6,
    adsMs: 290,
    trocaMs: 530,
    precisao: 40,
    controle: 45,
    mobilidade: 61,
    hipfire: 47,
    recuoV: 0.58,
    recuoH: 0.28,
    disparo: ['automatico', 'rajada'],
    procedencia: 'curado',
  },
  {
    id: 'sg-553r',
    nome: 'SG 553R',
    categoria: 'carabina',
    arquetipo: 'carabina-curta',
    resumo: 'Três tiros de perto e degraus generosos: a carabina mais agressiva do vão curto.',
    dano: [
      [33.4, 0],
      [25, 9],
      [20, 21],
      [16.7, 36],
      [14.3, 75],
    ],
    rpm: 720,
    velocidade: 519,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.75,
    recargaVazia: 3.45,
    adsMs: 285,
    trocaMs: 525,
    precisao: 33,
    controle: 40,
    mobilidade: 63,
    hipfire: 48,
    recuoV: 0.62,
    recuoH: 0.3,
    disparo: ['automatico', 'rajada'],
    procedencia: 'curado',
  },
  {
    id: 'sor-300sc',
    nome: 'SOR-300SC',
    categoria: 'carabina',
    arquetipo: 'carabina-curta',
    resumo: 'Versão encurtada do SOR: mantém o recuo domado da família em um corpo mais leve.',
    temporada: 1,
    dano: [
      [25, 0],
      [21.5, 9],
      [17.7, 21],
      [16.7, 36],
      [14.3, 75],
    ],
    rpm: 700,
    velocidade: 680,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.6,
    recargaVazia: 3.3,
    adsMs: 275,
    trocaMs: 515,
    precisao: 44,
    controle: 50,
    mobilidade: 64,
    hipfire: 47,
    recuoV: 0.48,
    recuoH: 0.22,
    disparo: ['automatico', 'rajada', 'semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'm277',
    nome: 'M277',
    categoria: 'carabina',
    arquetipo: 'carabina-curta',
    resumo: 'Dano plano em toda a distância: o mesmo número de tiros de 5 a 75 metros.',
    dano: [[25, 0]],
    rpm: 720,
    velocidade: 599,
    headshot: 1.35,
    carregador: 25,
    recarga: 2.7,
    recargaVazia: 3.4,
    adsMs: 300,
    trocaMs: 540,
    precisao: 41,
    controle: 43,
    mobilidade: 58,
    hipfire: 45,
    recuoV: 0.6,
    recuoH: 0.28,
    disparo: ['automatico', 'semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'brod-3',
    nome: 'BROD 3',
    categoria: 'carabina',
    arquetipo: 'carabina-curta',
    resumo: 'Carabina da Temporada 4: cadência média com recuo bastante previsível.',
    dano: [
      [25, 0],
      [20, 21],
      [16.7, 60],
    ],
    rpm: 750,
    velocidade: 660,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.65,
    recargaVazia: 3.35,
    adsMs: 285,
    trocaMs: 520,
    precisao: 43,
    controle: 47,
    mobilidade: 62,
    hipfire: 47,
    recuoV: 0.52,
    recuoH: 0.24,
    disparo: ['automatico', 'rajada'],
    temporada: 4,
    procedencia: 'curado',
  },
];

/* ------------------------------ Submetralhadoras ------------------------------ */

const SMGS: EntradaArma[] = [
  {
    id: 'scw-10',
    nome: 'SCW-10',
    categoria: 'smg',
    arquetipo: 'smg-compacta',
    resumo: 'Três tiros no vão curto: a submetralhadora que resolve o corredor mais rápido.',
    dano: [
      [33.4, 0],
      [25, 20],
      [20, 35],
      [16.7, 75],
    ],
    rpm: 800,
    velocidade: 428,
    arrasto: 1.15,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.4,
    recargaVazia: 3.05,
    adsMs: 235,
    trocaMs: 470,
    precisao: 30,
    controle: 52,
    mobilidade: 70,
    hipfire: 50,
    recuoV: 0.5,
    recuoH: 0.34,
    disparo: ['automatico'],
    procedencia: 'curado',
  },
  {
    id: 'kv9',
    nome: 'KV9',
    categoria: 'smg',
    arquetipo: 'smg-compacta',
    resumo: '1080 RPM: esvazia o carregador num piscar e vence qualquer duelo colado.',
    dano: [
      [25, 0],
      [20, 9],
      [16.7, 21],
      [14.3, 36],
      [12.5, 75],
    ],
    rpm: 1080,
    velocidade: 348,
    arrasto: 1.2,
    headshot: 1.35,
    carregador: 17,
    recarga: 2.9,
    recargaVazia: 3.5,
    adsMs: 250,
    trocaMs: 480,
    precisao: 23,
    controle: 62,
    mobilidade: 68,
    hipfire: 47,
    recuoV: 0.42,
    recuoH: 0.38,
    disparo: ['automatico'],
    procedencia: 'jogo',
  },
  {
    id: 'pw7a2',
    nome: 'PW7A2',
    categoria: 'smg',
    arquetipo: 'smg-pdw',
    resumo: 'Cadência altíssima com dano baixo — brilha com controle de recuo e alvos colados.',
    dano: [
      [16.7, 0],
      [14.3, 21],
      [12.5, 75],
    ],
    rpm: 947,
    velocidade: 600,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.97,
    recargaVazia: 3.6,
    adsMs: 240,
    trocaMs: 465,
    precisao: 35,
    controle: 58,
    mobilidade: 68,
    hipfire: 47,
    recuoV: 0.36,
    recuoH: 0.24,
    disparo: ['automatico'],
    procedencia: 'jogo',
  },
  {
    id: 'pw5a3',
    nome: 'PW5A3',
    categoria: 'smg',
    arquetipo: 'smg-compacta',
    resumo: 'Clássica de 9 mm: recuo domado e mira rápida, para quem prefere estabilidade.',
    dano: [
      [25, 0],
      [20, 9],
      [16.7, 21],
      [14.3, 36],
      [12.5, 75],
    ],
    rpm: 771,
    velocidade: 432,
    arrasto: 1.15,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.55,
    recargaVazia: 3.2,
    adsMs: 235,
    trocaMs: 460,
    precisao: 38,
    controle: 60,
    mobilidade: 70,
    hipfire: 48,
    recuoV: 0.38,
    recuoH: 0.22,
    disparo: ['automatico', 'rajada', 'semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'sgx',
    nome: 'SGX',
    categoria: 'smg',
    arquetipo: 'smg-pdw',
    resumo: 'Muito compacta e estável, com a bala mais lenta do arsenal — mire adiantado.',
    dano: [
      [25, 0],
      [20, 9],
      [16.7, 21],
      [14.3, 36],
      [12.5, 75],
    ],
    rpm: 830,
    velocidade: 402,
    arrasto: 1.2,
    headshot: 1.35,
    carregador: 25,
    recarga: 2.45,
    recargaVazia: 3.1,
    adsMs: 225,
    trocaMs: 450,
    precisao: 32,
    controle: 61,
    mobilidade: 73,
    hipfire: 52,
    recuoV: 0.4,
    recuoH: 0.3,
    disparo: ['automatico'],
    procedencia: 'curado',
  },
  {
    id: 'sl9',
    nome: 'SL9',
    categoria: 'smg',
    arquetipo: 'smg-pdw',
    resumo: 'Cadência baixa para uma SMG: troca velocidade de tiro por consistência.',
    dano: [
      [25, 0],
      [20, 9],
      [16.7, 21],
      [14.3, 36],
      [12.5, 75],
    ],
    rpm: 675,
    velocidade: 510,
    arrasto: 1.1,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.6,
    recargaVazia: 3.25,
    adsMs: 245,
    trocaMs: 470,
    precisao: 42,
    controle: 64,
    mobilidade: 66,
    hipfire: 46,
    recuoV: 0.34,
    recuoH: 0.2,
    disparo: ['automatico', 'semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'umg-40',
    nome: 'UMG-40',
    categoria: 'smg',
    arquetipo: 'smg-compacta',
    resumo: 'Calibre grosso e cadência baixa: a SMG que mais se parece com um fuzil.',
    dano: [
      [25, 0],
      [21.5, 9],
      [17.7, 21],
      [16.7, 36],
      [14.3, 75],
    ],
    rpm: 635,
    velocidade: 488,
    arrasto: 1.15,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.92,
    recargaVazia: 3.55,
    adsMs: 250,
    trocaMs: 475,
    precisao: 49,
    controle: 49,
    mobilidade: 68,
    hipfire: 47,
    recuoV: 0.54,
    recuoH: 0.26,
    disparo: ['automatico', 'semiautomatico'],
    procedencia: 'jogo',
  },
  {
    id: 'usg-90',
    nome: 'USG-90',
    categoria: 'smg',
    arquetipo: 'smg-pdw',
    resumo: 'Cinquenta tiros no pente e recuo curto: sustenta briga longa sem recarregar.',
    dano: [
      [20, 0],
      [17.7, 9],
      [15, 21],
      [14.3, 36],
      [12.5, 75],
    ],
    rpm: 900,
    velocidade: 570,
    headshot: 1.35,
    carregador: 50,
    recarga: 3.17,
    recargaVazia: 3.8,
    adsMs: 260,
    trocaMs: 485,
    precisao: 33,
    controle: 57,
    mobilidade: 64,
    hipfire: 47,
    recuoV: 0.38,
    recuoH: 0.26,
    disparo: ['automatico'],
    procedencia: 'jogo',
  },
  {
    id: 'cz3a1',
    nome: 'CZ3A1',
    categoria: 'smg',
    arquetipo: 'smg-compacta',
    resumo: 'Submetralhadora tcheca da Temporada 2: cadência absurda e alcance curtíssimo.',
    dano: [
      [20, 0],
      [17.7, 9],
      [15, 21],
      [12.5, 60],
    ],
    rpm: 1150,
    velocidade: 380,
    arrasto: 1.2,
    headshot: 1.35,
    carregador: 30,
    recarga: 2.5,
    recargaVazia: 3.1,
    adsMs: 230,
    trocaMs: 455,
    precisao: 20,
    controle: 58,
    mobilidade: 72,
    hipfire: 50,
    recuoV: 0.44,
    recuoH: 0.4,
    disparo: ['automatico'],
    temporada: 2,
    procedencia: 'curado',
  },
  {
    id: 'pp-19',
    nome: 'PP-19',
    categoria: 'smg',
    arquetipo: 'smg-compacta',
    resumo: 'Carregador helicoidal da Temporada 3: 53 tiros e tiro de quadril confiável.',
    dano: [
      [20, 0],
      [16.7, 15],
      [14.3, 50],
    ],
    rpm: 700,
    velocidade: 400,
    arrasto: 1.15,
    headshot: 1.35,
    carregador: 53,
    recarga: 3.1,
    recargaVazia: 3.75,
    adsMs: 255,
    trocaMs: 480,
    precisao: 36,
    controle: 60,
    mobilidade: 64,
    hipfire: 52,
    recuoV: 0.4,
    recuoH: 0.24,
    disparo: ['automatico'],
    temporada: 3,
    procedencia: 'curado',
  },
];

/* ------------------------------- Metralhadoras ------------------------------- */

const LMGS: EntradaArma[] = [
  {
    id: 'drs-iar',
    nome: 'DRS-IAR',
    categoria: 'lmg',
    arquetipo: 'lmg-leve',
    resumo: 'Metralhadora leve que maneja como fuzil — a porta de entrada do Suporte.',
    dano: [
      [25, 0],
      [20, 35],
    ],
    rpm: 771,
    velocidade: 720,
    headshot: 1.35,
    carregador: 45,
    recarga: 4.2,
    recargaVazia: 5.1,
    adsMs: 380,
    trocaMs: 680,
    precisao: 44,
    controle: 52,
    mobilidade: 44,
    hipfire: 34,
    recuoV: 0.5,
    recuoH: 0.26,
    disparo: ['automatico'],
    procedencia: 'curado',
  },
  {
    id: 'kts100-mk8',
    nome: 'KTS100 MK8',
    categoria: 'lmg',
    arquetipo: 'lmg-caixa',
    resumo: 'Cadência baixa, recuo mínimo e a maior velocidade de bala: supressão cirúrgica.',
    dano: [
      [25, 0],
      [20, 21],
      [16.7, 75],
    ],
    rpm: 514,
    velocidade: 840,
    headshot: 1.35,
    carregador: 60,
    recarga: 5.6,
    recargaVazia: 6.6,
    adsMs: 440,
    trocaMs: 760,
    precisao: 52,
    controle: 58,
    mobilidade: 32,
    hipfire: 26,
    recuoV: 0.4,
    recuoH: 0.18,
    disparo: ['automatico'],
    procedencia: 'curado',
  },
  {
    id: 'rpkm',
    nome: 'RPKM',
    categoria: 'lmg',
    arquetipo: 'lmg-leve',
    resumo: 'Três tiros de perto com carregador de 40: agressiva para uma metralhadora.',
    dano: [
      [33.4, 0],
      [27.3, 9],
      [21.5, 21],
      [20, 36],
      [16.7, 75],
    ],
    rpm: 553,
    velocidade: 670,
    arrasto: 1.05,
    headshot: 1.35,
    carregador: 40,
    recarga: 3.28,
    recargaVazia: 4.15,
    adsMs: 420,
    trocaMs: 700,
    precisao: 41,
    controle: 45,
    mobilidade: 38,
    hipfire: 34,
    recuoV: 0.66,
    recuoH: 0.32,
    disparo: ['automatico', 'semiautomatico'],
    procedencia: 'jogo',
  },
  {
    id: 'm123k',
    nome: 'M123K',
    categoria: 'lmg',
    arquetipo: 'lmg-caixa',
    resumo: 'Cem tiros na caixa e cadência alta: feita para prender o inimigo atrás da cobertura.',
    dano: [
      [25, 0],
      [20, 21],
      [16.7, 75],
    ],
    rpm: 830,
    velocidade: 670,
    headshot: 1.35,
    carregador: 100,
    recarga: 7.43,
    recargaVazia: 8.4,
    adsMs: 470,
    trocaMs: 800,
    precisao: 21,
    controle: 55,
    mobilidade: 34,
    hipfire: 34,
    recuoV: 0.46,
    recuoH: 0.3,
    disparo: ['automatico'],
    procedencia: 'jogo',
  },
  {
    id: 'm250',
    nome: 'M250',
    categoria: 'lmg',
    arquetipo: 'lmg-caixa',
    resumo: 'Dano constante em qualquer distância — quatro tiros a 5 ou a 100 metros.',
    dano: [[25, 0]],
    rpm: 675,
    velocidade: 760,
    headshot: 1.35,
    carregador: 50,
    recarga: 6.13,
    recargaVazia: 7.1,
    adsMs: 460,
    trocaMs: 780,
    precisao: 26,
    controle: 43,
    mobilidade: 28,
    hipfire: 22,
    recuoV: 0.58,
    recuoH: 0.28,
    disparo: ['automatico'],
    procedencia: 'jogo',
  },
  {
    id: 'l110',
    nome: 'L110',
    categoria: 'lmg',
    arquetipo: 'lmg-caixa',
    resumo: 'Boa cadência e bala rápida: o meio-termo entre supressão e precisão.',
    dano: [
      [25, 0],
      [20, 35],
    ],
    rpm: 720,
    velocidade: 780,
    headshot: 1.35,
    carregador: 75,
    recarga: 6.4,
    recargaVazia: 7.4,
    adsMs: 450,
    trocaMs: 770,
    precisao: 30,
    controle: 48,
    mobilidade: 30,
    hipfire: 26,
    recuoV: 0.5,
    recuoH: 0.26,
    disparo: ['automatico'],
    procedencia: 'curado',
  },
  {
    id: 'm60',
    nome: 'M/60',
    categoria: 'lmg',
    arquetipo: 'lmg-caixa',
    resumo: 'Metralhadora de 7,62 mm: três tiros derrubam, ao custo de peso e cadência.',
    dano: [
      [33.4, 0],
      [25, 35],
    ],
    rpm: 514,
    velocidade: 720,
    arrasto: 1.05,
    headshot: 1.35,
    carregador: 100,
    recarga: 7.8,
    recargaVazia: 8.8,
    adsMs: 490,
    trocaMs: 820,
    precisao: 34,
    controle: 36,
    mobilidade: 24,
    hipfire: 24,
    recuoV: 0.84,
    recuoH: 0.34,
    disparo: ['automatico'],
    procedencia: 'curado',
  },
  {
    id: 'm240l',
    nome: 'M240L',
    categoria: 'lmg',
    arquetipo: 'lmg-caixa',
    resumo: 'A mais pesada do arsenal: dano de 7,62 mm sustentado sobre bipé.',
    dano: [
      [33.4, 0],
      [25, 36],
    ],
    rpm: 600,
    velocidade: 630,
    arrasto: 1.05,
    headshot: 1.35,
    carregador: 100,
    recarga: 8.1,
    recargaVazia: 9.1,
    adsMs: 500,
    trocaMs: 840,
    precisao: 32,
    controle: 34,
    mobilidade: 22,
    hipfire: 22,
    recuoV: 0.88,
    recuoH: 0.36,
    disparo: ['automatico'],
    procedencia: 'curado',
  },
  {
    id: 'm121-a2',
    nome: 'M121 A2',
    categoria: 'lmg',
    arquetipo: 'lmg-caixa',
    resumo: 'Metralhadora de uso geral da Temporada 2: dano de 7,62 mm e peso à altura.',
    dano: [
      [33.4, 0],
      [25, 35],
    ],
    rpm: 550,
    velocidade: 700,
    arrasto: 1.05,
    headshot: 1.35,
    carregador: 100,
    recarga: 7.6,
    recargaVazia: 8.6,
    adsMs: 485,
    trocaMs: 810,
    precisao: 36,
    controle: 38,
    mobilidade: 25,
    hipfire: 24,
    recuoV: 0.82,
    recuoH: 0.33,
    disparo: ['automatico'],
    temporada: 2,
    procedencia: 'curado',
  },
  {
    id: 'rpk-74m',
    nome: 'RPK-74M',
    categoria: 'lmg',
    arquetipo: 'lmg-leve',
    resumo: 'Metralhadora leve da Temporada 3: bala rápida e manejo próximo ao de um fuzil.',
    dano: [
      [25, 0],
      [20, 30],
    ],
    rpm: 600,
    velocidade: 900,
    headshot: 1.35,
    carregador: 45,
    recarga: 3.5,
    recargaVazia: 4.4,
    adsMs: 400,
    trocaMs: 690,
    precisao: 48,
    controle: 50,
    mobilidade: 40,
    hipfire: 32,
    recuoV: 0.54,
    recuoH: 0.24,
    disparo: ['automatico', 'semiautomatico'],
    temporada: 3,
    procedencia: 'curado',
  },
];

/* ---------------------- Rifles de precisão semiautomáticos ---------------------- */

const DMRS: EntradaArma[] = [
  {
    id: 'lmr27',
    nome: 'LMR27',
    categoria: 'dmr',
    arquetipo: 'dmr',
    resumo: 'Semiautomático de cadência alta e dano bastante estável na distância.',
    dano: [
      [28.6, 0],
      [27.3, 21],
      [25, 75],
    ],
    rpm: 450,
    velocidade: 880,
    headshot: 1.35,
    carregador: 10,
    recarga: 3.07,
    recargaVazia: 3.85,
    adsMs: 480,
    trocaMs: 700,
    precisao: 66,
    controle: 31,
    mobilidade: 52,
    hipfire: 40,
    recuoV: 0.9,
    recuoH: 0.2,
    disparo: ['semiautomatico'],
    procedencia: 'jogo',
  },
  {
    id: 'm39-emr',
    nome: 'M39 EMR',
    categoria: 'dmr',
    arquetipo: 'dmr',
    resumo: 'Clássico de 7,62 mm: três tiros ao peito e mira confortável na média distância.',
    dano: [
      [33.4, 0],
      [30, 50],
      [27.3, 100],
    ],
    rpm: 380,
    velocidade: 850,
    arrasto: 1.05,
    headshot: 1.5,
    carregador: 20,
    recarga: 3.2,
    recargaVazia: 4.0,
    adsMs: 490,
    trocaMs: 710,
    precisao: 72,
    controle: 34,
    mobilidade: 48,
    hipfire: 36,
    recuoV: 1.0,
    recuoH: 0.22,
    disparo: ['semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'svdm',
    nome: 'SVDM',
    categoria: 'dmr',
    arquetipo: 'dmr',
    resumo: 'Dragunov moderno: alcance longo, recuo alto e recuperação lenta entre tiros.',
    dano: [
      [33.4, 0],
      [30, 50],
      [27.3, 100],
    ],
    rpm: 360,
    velocidade: 830,
    arrasto: 1.05,
    headshot: 1.5,
    carregador: 10,
    recarga: 3.35,
    recargaVazia: 4.2,
    adsMs: 505,
    trocaMs: 720,
    precisao: 74,
    controle: 28,
    mobilidade: 46,
    hipfire: 34,
    recuoV: 1.1,
    recuoH: 0.26,
    disparo: ['semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'svk-86',
    nome: 'SVK-8.6',
    categoria: 'dmr',
    arquetipo: 'dmr',
    resumo: 'Calibre .338 semiautomático: dois tiros ao peito, com recuo à altura.',
    dano: [
      [50, 0],
      [45, 60],
      [40, 120],
    ],
    rpm: 260,
    velocidade: 900,
    arrasto: 0.9,
    headshot: 1.7,
    carregador: 10,
    recarga: 3.5,
    recargaVazia: 4.35,
    adsMs: 540,
    trocaMs: 750,
    precisao: 82,
    controle: 22,
    mobilidade: 42,
    hipfire: 30,
    recuoV: 1.35,
    recuoH: 0.28,
    disparo: ['semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'vssm',
    nome: 'VSSM',
    categoria: 'dmr',
    arquetipo: 'dmr',
    resumo: 'DMR subsônico da Temporada 4: silencioso de fábrica, com bala lenta e pesada.',
    dano: [
      [28.6, 0],
      [25, 30],
      [20, 60],
    ],
    rpm: 600,
    velocidade: 295,
    arrasto: 1.3,
    headshot: 1.5,
    carregador: 20,
    recarga: 2.9,
    recargaVazia: 3.7,
    adsMs: 430,
    trocaMs: 660,
    precisao: 60,
    controle: 44,
    mobilidade: 56,
    hipfire: 42,
    recuoV: 0.7,
    recuoH: 0.24,
    disparo: ['automatico', 'semiautomatico'],
    temporada: 4,
    procedencia: 'curado',
  },
  {
    id: 'grt-cps',
    nome: 'GRT-CPS',
    categoria: 'dmr',
    arquetipo: 'dmr',
    resumo: 'DMR da Temporada 2: cadência baixa, bala veloz e dano firme na distância.',
    dano: [
      [33.4, 0],
      [28.6, 45],
      [25, 90],
    ],
    rpm: 400,
    velocidade: 860,
    headshot: 1.5,
    carregador: 15,
    recarga: 3.15,
    recargaVazia: 3.95,
    adsMs: 485,
    trocaMs: 705,
    precisao: 70,
    controle: 33,
    mobilidade: 50,
    hipfire: 36,
    recuoV: 0.95,
    recuoH: 0.2,
    disparo: ['semiautomatico'],
    temporada: 2,
    procedencia: 'curado',
  },
];

/* ----------------------------- Rifles de precisão ----------------------------- */

const SNIPERS: EntradaArma[] = [
  {
    id: 'm2010-esr',
    nome: 'M2010 ESR',
    categoria: 'sniper',
    arquetipo: 'sniper-ferrolho',
    resumo: 'Ferrolho que mata com um tiro ao peito a partir de 75 m — o padrão do Recon.',
    dano: [
      [80, 0],
      [100, 75],
      [62.5, 160],
    ],
    rpm: 44,
    velocidade: 800,
    arrasto: 0.9,
    headshot: 1.7,
    carregador: 5,
    recarga: 3.93,
    recargaVazia: 4.8,
    adsMs: 650,
    trocaMs: 900,
    precisao: 100,
    controle: 27,
    mobilidade: 50,
    hipfire: 34,
    recuoV: 2.2,
    recuoH: 0.3,
    disparo: ['ferrolho'],
    procedencia: 'jogo',
  },
  {
    id: 'sv-98',
    nome: 'SV-98',
    categoria: 'sniper',
    arquetipo: 'sniper-ferrolho',
    resumo: 'Alcança o tiro único mais cedo, a 54 m, mas perde força depois de 125 m.',
    dano: [
      [80, 0],
      [100, 54],
      [62.5, 125],
    ],
    rpm: 38,
    velocidade: 720,
    arrasto: 0.95,
    headshot: 1.7,
    carregador: 10,
    recarga: 3.97,
    recargaVazia: 4.85,
    adsMs: 680,
    trocaMs: 920,
    precisao: 100,
    controle: 33,
    mobilidade: 46,
    hipfire: 34,
    recuoV: 2.1,
    recuoH: 0.28,
    disparo: ['ferrolho'],
    procedencia: 'jogo',
  },
  {
    id: 'psr',
    nome: 'PSR',
    categoria: 'sniper',
    arquetipo: 'sniper-ferrolho',
    resumo: 'Calibre .338: tiro único a partir de 40 m e a trajetória mais reta do jogo.',
    dano: [
      [95, 0],
      [100, 40],
      [75, 150],
    ],
    rpm: 34,
    velocidade: 880,
    arrasto: 0.85,
    headshot: 1.7,
    carregador: 5,
    recarga: 4.3,
    recargaVazia: 5.2,
    adsMs: 720,
    trocaMs: 960,
    precisao: 100,
    controle: 20,
    mobilidade: 40,
    hipfire: 30,
    recuoV: 2.6,
    recuoH: 0.32,
    disparo: ['ferrolho'],
    procedencia: 'curado',
  },
  {
    id: 'mini-scout',
    nome: 'Mini Scout',
    categoria: 'sniper',
    arquetipo: 'sniper-ferrolho',
    resumo: 'Ferrolho leve para sniper agressivo: mira rápida ao custo de alcance letal.',
    temporada: 1,
    dano: [
      [70, 0],
      [80, 40],
      [55, 110],
    ],
    rpm: 55,
    velocidade: 640,
    arrasto: 1.0,
    headshot: 1.7,
    carregador: 5,
    recarga: 3.5,
    recargaVazia: 4.35,
    adsMs: 520,
    trocaMs: 780,
    precisao: 92,
    controle: 40,
    mobilidade: 62,
    hipfire: 40,
    recuoV: 1.7,
    recuoH: 0.26,
    disparo: ['ferrolho'],
    procedencia: 'curado',
  },
  {
    id: 'l115',
    nome: 'L115',
    categoria: 'sniper',
    arquetipo: 'sniper-ferrolho',
    resumo: 'Ferrolho .338 da Temporada 3: tiro único cedo e trajetória bastante reta.',
    dano: [
      [85, 0],
      [100, 50],
      [70, 140],
    ],
    rpm: 40,
    velocidade: 850,
    arrasto: 0.87,
    headshot: 1.7,
    carregador: 5,
    recarga: 4.1,
    recargaVazia: 5.0,
    adsMs: 690,
    trocaMs: 930,
    precisao: 100,
    controle: 24,
    mobilidade: 43,
    hipfire: 32,
    recuoV: 2.4,
    recuoH: 0.3,
    disparo: ['ferrolho'],
    temporada: 3,
    procedencia: 'curado',
  },
  {
    id: 'interdictor',
    nome: 'Interdictor',
    categoria: 'sniper',
    arquetipo: 'sniper-ferrolho',
    resumo: 'Antimaterial da Temporada 4: um tiro ao peito em qualquer distância, e lentíssima.',
    dano: [
      [100, 0],
      [80, 120],
    ],
    rpm: 30,
    velocidade: 780,
    arrasto: 0.8,
    headshot: 1.7,
    carregador: 5,
    recarga: 4.6,
    recargaVazia: 5.6,
    adsMs: 780,
    trocaMs: 1020,
    precisao: 100,
    controle: 16,
    mobilidade: 34,
    hipfire: 26,
    recuoV: 3.1,
    recuoH: 0.36,
    disparo: ['ferrolho'],
    temporada: 4,
    procedencia: 'curado',
  },
];

/* --------------------------------- Escopetas --------------------------------- */

const ESCOPETAS: EntradaArma[] = [
  {
    id: 'm1014',
    nome: 'M1014',
    categoria: 'escopeta',
    arquetipo: 'escopeta',
    resumo: 'Semiautomática: tiro único até 9 m e disparos de acompanhamento rápidos.',
    dano: [
      [7.2, 0],
      [5, 9],
      [3.1, 16],
      [2.3, 22],
    ],
    projeteis: 15,
    rpm: 200,
    velocidade: 400,
    arrasto: 1.6,
    headshot: 1.0,
    carregador: 6,
    recarga: 0.4,
    recargaVazia: 0.9,
    adsMs: 410,
    trocaMs: 640,
    precisao: 10,
    controle: 10,
    mobilidade: 52,
    hipfire: 40,
    recuoV: 1.6,
    recuoH: 0.5,
    disparo: ['semiautomatico'],
    procedencia: 'jogo',
  },
  {
    id: '18-5ks-k',
    nome: '18.5KS-K',
    categoria: 'escopeta',
    arquetipo: 'escopeta',
    resumo: 'Semiautomática de cadência alta: perdoa o erro de mira no vão colado.',
    dano: [
      [6.8, 0],
      [4.7, 9],
      [3, 16],
      [2.2, 22],
    ],
    projeteis: 15,
    rpm: 240,
    velocidade: 390,
    arrasto: 1.6,
    headshot: 1.0,
    carregador: 7,
    recarga: 0.42,
    recargaVazia: 0.95,
    adsMs: 400,
    trocaMs: 630,
    precisao: 10,
    controle: 12,
    mobilidade: 54,
    hipfire: 42,
    recuoV: 1.5,
    recuoH: 0.52,
    disparo: ['semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'm87a1',
    nome: 'M87A1',
    categoria: 'escopeta',
    arquetipo: 'escopeta',
    resumo: 'Bombeamento pesado: o maior alcance letal entre as escopetas, um tiro por vez.',
    dano: [
      [9, 0],
      [6.5, 10],
      [4, 18],
      [2.6, 25],
    ],
    projeteis: 12,
    rpm: 75,
    velocidade: 420,
    arrasto: 1.55,
    headshot: 1.0,
    carregador: 6,
    recarga: 0.45,
    recargaVazia: 1.0,
    adsMs: 430,
    trocaMs: 660,
    precisao: 14,
    controle: 8,
    mobilidade: 48,
    hipfire: 38,
    recuoV: 2.0,
    recuoH: 0.55,
    disparo: ['bombeamento'],
    procedencia: 'curado',
  },
  {
    id: 'db-12',
    nome: 'DB-12',
    categoria: 'escopeta',
    arquetipo: 'escopeta',
    resumo: 'Cano duplo: dois tiros devastadores e uma recarga que expõe demais.',
    temporada: 1,
    dano: [
      [10, 0],
      [7, 10],
      [4.5, 18],
      [2.8, 24],
    ],
    projeteis: 12,
    rpm: 300,
    velocidade: 410,
    arrasto: 1.55,
    headshot: 1.0,
    carregador: 2,
    recarga: 2.4,
    recargaVazia: 2.4,
    adsMs: 380,
    trocaMs: 600,
    precisao: 12,
    controle: 6,
    mobilidade: 58,
    hipfire: 44,
    recuoV: 2.2,
    recuoH: 0.6,
    disparo: ['semiautomatico'],
    procedencia: 'curado',
  },
];

/* --------------------------------- Pistolas --------------------------------- */

const PISTOLAS: EntradaArma[] = [
  {
    id: 'm45a1',
    nome: 'M45A1',
    categoria: 'pistola',
    arquetipo: 'pistola',
    resumo: 'Calibre .45: três tiros de perto, saque rápido e bala lenta.',
    dano: [
      [33.4, 0],
      [25, 9],
      [20, 21],
      [16.7, 36],
      [14.3, 54],
      [12.5, 75],
    ],
    rpm: 327,
    velocidade: 336,
    arrasto: 1.25,
    headshot: 1.35,
    carregador: 8,
    recarga: 2.0,
    recargaVazia: 2.5,
    adsMs: 200,
    trocaMs: 380,
    precisao: 51,
    controle: 17,
    mobilidade: 72,
    hipfire: 54,
    recuoV: 0.9,
    recuoH: 0.3,
    disparo: ['semiautomatico'],
    procedencia: 'jogo',
  },
  {
    id: 'es-57',
    nome: 'ES 5.7',
    categoria: 'pistola',
    arquetipo: 'pistola',
    resumo: 'Vinte tiros de calibre pequeno e alta velocidade: a pistola de maior alcance útil.',
    dano: [
      [20, 0],
      [17.7, 9],
      [15, 21],
      [14.3, 36],
      [12.5, 75],
    ],
    rpm: 450,
    velocidade: 650,
    headshot: 1.35,
    carregador: 20,
    recarga: 2.2,
    recargaVazia: 2.7,
    adsMs: 220,
    trocaMs: 400,
    precisao: 55,
    controle: 31,
    mobilidade: 79,
    hipfire: 54,
    recuoV: 0.6,
    recuoH: 0.22,
    disparo: ['semiautomatico'],
    procedencia: 'jogo',
  },
  {
    id: 'm44',
    nome: 'M44',
    categoria: 'pistola',
    arquetipo: 'revolver',
    resumo: 'Revólver magnum: dois tiros ao peito, seis tentativas e recuo brutal.',
    dano: [
      [66.7, 0],
      [59.9, 9],
      [33.4, 21],
      [25, 75],
    ],
    rpm: 164,
    velocidade: 440,
    arrasto: 1.1,
    headshot: 1.35,
    carregador: 6,
    recarga: 3.4,
    recargaVazia: 3.4,
    adsMs: 250,
    trocaMs: 430,
    precisao: 22,
    controle: 2,
    mobilidade: 64,
    hipfire: 54,
    recuoV: 1.8,
    recuoH: 0.4,
    disparo: ['semiautomatico'],
    procedencia: 'jogo',
  },
  {
    id: 'p18',
    nome: 'P18',
    categoria: 'pistola',
    arquetipo: 'pistola',
    resumo: 'Pistola-metralhadora de bolso: rajada automática que se esvazia num instante.',
    dano: [
      [16.7, 0],
      [14.3, 9],
      [12.5, 21],
      [11.2, 36],
    ],
    rpm: 1100,
    velocidade: 380,
    arrasto: 1.25,
    headshot: 1.35,
    carregador: 17,
    recarga: 2.1,
    recargaVazia: 2.6,
    adsMs: 210,
    trocaMs: 390,
    precisao: 18,
    controle: 40,
    mobilidade: 76,
    hipfire: 56,
    recuoV: 0.5,
    recuoH: 0.44,
    disparo: ['automatico', 'semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'ggh-22',
    nome: 'GGH-22',
    categoria: 'pistola',
    arquetipo: 'pistola',
    resumo: 'Pistola de serviço equilibrada, com bom dano de perto e recuo controlável.',
    temporada: 1,
    dano: [
      [25, 0],
      [20, 9],
      [16.7, 21],
      [14.3, 36],
      [12.5, 75],
    ],
    rpm: 400,
    velocidade: 420,
    arrasto: 1.2,
    headshot: 1.35,
    carregador: 15,
    recarga: 2.15,
    recargaVazia: 2.65,
    adsMs: 205,
    trocaMs: 385,
    precisao: 48,
    controle: 34,
    mobilidade: 75,
    hipfire: 54,
    recuoV: 0.7,
    recuoH: 0.26,
    disparo: ['semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'm357-trait',
    nome: 'M357 Trait',
    categoria: 'pistola',
    arquetipo: 'revolver',
    resumo: 'Revólver leve de oito tiros: menos coice que o M44, com dano ainda alto.',
    temporada: 1,
    dano: [
      [50, 0],
      [40, 15],
      [33.4, 30],
    ],
    rpm: 220,
    velocidade: 400,
    arrasto: 1.15,
    headshot: 1.35,
    carregador: 8,
    recarga: 3.1,
    recargaVazia: 3.1,
    adsMs: 235,
    trocaMs: 415,
    precisao: 30,
    controle: 12,
    mobilidade: 68,
    hipfire: 54,
    recuoV: 1.4,
    recuoH: 0.34,
    disparo: ['semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'vz-61',
    nome: 'vz. 61',
    categoria: 'pistola',
    arquetipo: 'pistola',
    resumo: 'Skorpion da Temporada 2: pistola-metralhadora de bolso com rajada frenética.',
    dano: [
      [16.7, 0],
      [14.3, 9],
      [12.5, 25],
    ],
    rpm: 850,
    velocidade: 320,
    arrasto: 1.3,
    headshot: 1.35,
    carregador: 20,
    recarga: 2.25,
    recargaVazia: 2.8,
    adsMs: 215,
    trocaMs: 395,
    precisao: 20,
    controle: 44,
    mobilidade: 74,
    hipfire: 56,
    recuoV: 0.48,
    recuoH: 0.4,
    disparo: ['automatico', 'semiautomatico'],
    temporada: 2,
    procedencia: 'curado',
  },
];

/* ------------------------------- Corpo a corpo ------------------------------- */

const CORPO_A_CORPO: EntradaArma[] = [
  {
    id: 'kbr-mark-ii',
    nome: 'KBR Mark II',
    categoria: 'corpo-a-corpo',
    arquetipo: 'faca',
    resumo: 'Faca padrão: golpe rápido e, pelas costas, eliminação imediata.',
    dano: [[50, 0]],
    rpm: 100,
    velocidade: 0,
    headshot: 1,
    carregador: 0,
    recarga: 0,
    recargaVazia: 0,
    adsMs: 0,
    trocaMs: 300,
    precisao: 0,
    controle: 0,
    mobilidade: 100,
    hipfire: 100,
    recuoV: 0,
    recuoH: 0,
    disparo: ['semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'bighorn-hk-16',
    nome: 'Bighorn HK-16',
    categoria: 'corpo-a-corpo',
    arquetipo: 'faca',
    resumo: 'Lâmina maior: golpe um pouco mais lento e mais alcance.',
    dano: [[55, 0]],
    rpm: 88,
    velocidade: 0,
    headshot: 1,
    carregador: 0,
    recarga: 0,
    recargaVazia: 0,
    adsMs: 0,
    trocaMs: 320,
    precisao: 0,
    controle: 0,
    mobilidade: 96,
    hipfire: 100,
    recuoV: 0,
    recuoH: 0,
    disparo: ['semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'marreta-14lb',
    nome: 'Marreta de 14 lb',
    categoria: 'corpo-a-corpo',
    arquetipo: 'contundente',
    resumo: 'Pancada pesada que derruba de frente — e abre paredes finas.',
    dano: [[100, 0]],
    rpm: 50,
    velocidade: 0,
    headshot: 1,
    carregador: 0,
    recarga: 0,
    recargaVazia: 0,
    adsMs: 0,
    trocaMs: 480,
    precisao: 0,
    controle: 0,
    mobilidade: 82,
    hipfire: 100,
    recuoV: 0,
    recuoH: 0,
    disparo: ['semiautomatico'],
    procedencia: 'curado',
  },
  {
    id: 'nomad-cx-12',
    nome: 'Nomad CX-12',
    categoria: 'corpo-a-corpo',
    arquetipo: 'contundente',
    resumo: 'Machado de escalada: bom dano e serve para subir paredes marcadas.',
    dano: [[70, 0]],
    rpm: 70,
    velocidade: 0,
    headshot: 1,
    carregador: 0,
    recarga: 0,
    recargaVazia: 0,
    adsMs: 0,
    trocaMs: 380,
    precisao: 0,
    controle: 0,
    mobilidade: 90,
    hipfire: 100,
    recuoV: 0,
    recuoH: 0,
    disparo: ['semiautomatico'],
    temporada: 1,
    procedencia: 'curado',
  },
  {
    id: 'ripper-14',
    nome: 'Ripper 14"',
    categoria: 'corpo-a-corpo',
    arquetipo: 'faca',
    resumo: 'Facão de 14 polegadas: o maior alcance do corpo a corpo.',
    dano: [[60, 0]],
    rpm: 78,
    velocidade: 0,
    headshot: 1,
    carregador: 0,
    recarga: 0,
    recargaVazia: 0,
    adsMs: 0,
    trocaMs: 340,
    precisao: 0,
    controle: 0,
    mobilidade: 92,
    hipfire: 100,
    recuoV: 0,
    recuoH: 0,
    disparo: ['semiautomatico'],
    temporada: 2,
    procedencia: 'curado',
  },
];

export const ARMAS: Arma[] = [
  ...FUZIS,
  ...CARABINAS,
  ...SMGS,
  ...LMGS,
  ...DMRS,
  ...SNIPERS,
  ...ESCOPETAS,
  ...PISTOLAS,
  ...CORPO_A_CORPO,
].map(montar);

export const ARMAS_POR_ID = new Map<string, Arma>(ARMAS.map((a) => [a.id, a]));

export const CATEGORIAS_ORDEM: CategoriaArma[] = [
  'ar',
  'carabina',
  'smg',
  'lmg',
  'dmr',
  'sniper',
  'escopeta',
  'pistola',
  'corpo-a-corpo',
];

/** Categorias que podem ocupar o slot de arma principal. */
export const CATEGORIAS_PRIMARIAS: CategoriaArma[] = [
  'ar',
  'carabina',
  'smg',
  'lmg',
  'dmr',
  'sniper',
  'escopeta',
];

export function armasDaCategoria(categoria: CategoriaArma): Arma[] {
  return ARMAS.filter((a) => a.categoria === categoria);
}

export function arquetiposExistentes(): ArquetipoArma[] {
  return [...new Set(ARMAS.map((a) => a.arquetipo))];
}
