import type { Gadget, IdClasse } from './tipos';

/* -------------------------------------------------------------------------- *
 * Equipamento por classe. Os nomes em português seguem a nomenclatura usada na
 * localização do jogo; o nome em inglês fica ao lado para conferência.
 * -------------------------------------------------------------------------- */

export const GADGETS: Gadget[] = [
  /* --------------------------------- Assalto --------------------------------- */
  {
    id: 'escada-assalto',
    nome: 'Escada de Assalto',
    nomeOriginal: 'Assault Ladder',
    classe: 'assalto',
    tipo: 'gadget',
    descricao: 'Abre uma rota vertical onde não havia — pega a defesa por um ângulo inesperado.',
    procedencia: 'jogo',
  },
  {
    id: 'farol-reaparecimento',
    nome: 'Farol de Reaparecimento',
    nomeOriginal: 'Deploy Beacon',
    classe: 'assalto',
    tipo: 'gadget',
    descricao: 'Ponto de renascimento para o esquadrão. Bem escondido, sustenta um flanco inteiro.',
    procedencia: 'jogo',
  },
  {
    id: 'lancador-arrombamento',
    nome: 'Lançador de Projétil de Arrombamento',
    nomeOriginal: 'Breaching Projectile Launcher',
    classe: 'assalto',
    tipo: 'gadget',
    descricao: 'Abre paredes e portas trancadas, criando entrada onde o inimigo não espera.',
    procedencia: 'jogo',
  },
  {
    id: 'lancador-alto-explosivo',
    nome: 'Lançador de Alto Explosivo',
    nomeOriginal: 'High Explosive Launcher',
    classe: 'assalto',
    tipo: 'gadget',
    descricao: 'Granada de alto explosivo para desalojar grupos entrincheirados.',
    procedencia: 'jogo',
  },
  {
    id: 'escopeta-incendiaria',
    nome: 'Escopeta de Munição Incendiária',
    nomeOriginal: 'Incendiary-Round Shotgun',
    classe: 'assalto',
    tipo: 'gadget',
    descricao: 'Acoplada à arma: incendeia um cômodo e nega passagem por alguns segundos.',
    procedencia: 'jogo',
  },
  {
    id: 'lancador-termobarico',
    nome: 'Lança-granadas Termobárico',
    nomeOriginal: 'Thermobaric Grenade Launcher',
    classe: 'assalto',
    tipo: 'gadget',
    descricao: 'Onda de pressão que limpa espaços fechados com brutalidade.',
    procedencia: 'jogo',
  },

  /* -------------------------------- Engenheiro -------------------------------- */
  {
    id: 'lancador-nao-guiado',
    nome: 'Lançador de Foguetes Não Guiado',
    nomeOriginal: 'Unguided Rocket Launcher',
    classe: 'engenheiro',
    tipo: 'gadget',
    descricao: 'Foguete burro de dano alto: exige mira própria e recompensa a paciência.',
    procedencia: 'jogo',
  },
  {
    id: 'lancador-guiado-mira',
    nome: 'Lançador Guiado por Mira',
    nomeOriginal: 'Aim-Guided Launcher',
    classe: 'engenheiro',
    tipo: 'gadget',
    descricao: 'O míssil segue para onde você mira — mantenha o alvo na retícula até o impacto.',
    procedencia: 'jogo',
  },
  {
    id: 'lancador-autoguiado',
    nome: 'Lançador Autoguiado',
    nomeOriginal: 'Auto-Guided Launcher',
    classe: 'engenheiro',
    tipo: 'gadget',
    descricao: 'Trava no veículo e persegue sozinho, ao custo de dano por disparo.',
    procedencia: 'jogo',
  },
  {
    id: 'lancador-antiaereo',
    nome: 'Lançador Antiaéreo',
    nomeOriginal: 'Air-Defense Launcher',
    classe: 'engenheiro',
    tipo: 'gadget',
    descricao: 'Especializado em helicóptero e caça: obriga a aviação a manter distância.',
    procedencia: 'jogo',
  },
  {
    id: 'lancador-longo-alcance',
    nome: 'Lançador de Longo Alcance',
    nomeOriginal: 'Long-Range Launcher',
    classe: 'engenheiro',
    tipo: 'gadget',
    descricao: 'Alcança blindados do outro lado do mapa, com tempo de voo considerável.',
    procedencia: 'jogo',
  },
  {
    id: 'mina-antiveiculo',
    nome: 'Mina Antiveículo',
    nomeOriginal: 'Anti-Vehicle Mine',
    classe: 'engenheiro',
    tipo: 'gadget',
    descricao: 'Nega estradas e acessos. Em conjunto, imobiliza um tanque inteiro.',
    procedencia: 'jogo',
  },
  {
    id: 'mina-sensor-acustico',
    nome: 'Mina AV com Sensor Acústico',
    nomeOriginal: 'Acoustic Sensor AV Mine',
    classe: 'engenheiro',
    tipo: 'gadget',
    descricao: 'Dispara pelo ruído do motor: não precisa ser pisada para detonar.',
    procedencia: 'jogo',
  },
  {
    id: 'mina-fio-tropeco',
    nome: 'Mina AV com Sensor de Fio de Tropeço',
    nomeOriginal: 'Tripwire Sensor AV Mine',
    classe: 'engenheiro',
    tipo: 'gadget',
    descricao: 'Estende um feixe pelo vão e detona quando o veículo o cruza.',
    procedencia: 'jogo',
  },
  {
    id: 'robo-eod',
    nome: 'Robô EOD',
    nomeOriginal: 'EOD Bot',
    classe: 'engenheiro',
    tipo: 'gadget',
    descricao: 'Repara veículos a distância e desarma explosivos sem expor o operador.',
    procedencia: 'jogo',
  },
  {
    id: 'caixa-suprimentos-veiculo',
    nome: 'Caixa de Suprimentos para Veículos',
    nomeOriginal: 'Vehicle Supply Crate',
    classe: 'engenheiro',
    tipo: 'gadget',
    descricao: 'Reabastece a blindagem aliada em campo, sem voltar à base.',
    procedencia: 'jogo',
  },

  /* --------------------------------- Suporte --------------------------------- */
  {
    id: 'desfibrilador',
    nome: 'Desfibrilador',
    nomeOriginal: 'Defibrillator',
    classe: 'suporte',
    tipo: 'gadget',
    descricao: 'Reanima o companheiro caído e devolve o esquadrão à briga sem perder terreno.',
    procedencia: 'jogo',
  },
  {
    id: 'bolsa-suprimentos',
    nome: 'Bolsa de Suprimentos',
    nomeOriginal: 'Supply Pouch',
    classe: 'suporte',
    tipo: 'gadget',
    descricao: 'Devolve munição e vida ao esquadrão em campo aberto.',
    procedencia: 'jogo',
  },
  {
    id: 'cobertura-implantavel',
    nome: 'Cobertura Implantável',
    nomeOriginal: 'Deployable Cover',
    classe: 'suporte',
    tipo: 'gadget',
    descricao: 'Cria proteção onde o mapa não oferece nenhuma — segura um avanço.',
    procedencia: 'jogo',
  },
  {
    id: 'morteiro-portatil',
    nome: 'Morteiro Portátil',
    nomeOriginal: 'Portable Mortar',
    classe: 'suporte',
    tipo: 'gadget',
    descricao: 'Fogo indireto sobre objetivos que você não consegue ver.',
    procedencia: 'jogo',
  },
  {
    id: 'lancador-fumaca',
    nome: 'Lança-granadas de Fumaça',
    nomeOriginal: 'Smoke Grenade Launcher',
    classe: 'suporte',
    tipo: 'gadget',
    descricao: 'Corta a linha de visão a distância e abre a travessia de um campo aberto.',
    procedencia: 'jogo',
  },
  {
    id: 'lancador-incendiario-aereo',
    nome: 'Lançador Incendiário de Explosão Aérea',
    nomeOriginal: 'Incendiary Airburst Launcher',
    classe: 'suporte',
    tipo: 'gadget',
    descricao: 'Explode no ar e chove fogo sobre quem está atrás da cobertura.',
    procedencia: 'jogo',
  },
  {
    id: 'interceptador-granadas',
    nome: 'Sistema de Interceptação de Granadas',
    nomeOriginal: 'Grenade Intercept System',
    classe: 'suporte',
    tipo: 'gadget',
    descricao: 'Derruba explosivos arremessados que entram no perímetro do esquadrão.',
    procedencia: 'jogo',
  },
  {
    id: 'interceptador-misseis',
    nome: 'Sistema de Interceptação de Mísseis',
    nomeOriginal: 'Missile Intercept System',
    classe: 'suporte',
    tipo: 'gadget',
    descricao: 'Protege a área de mísseis guiados — essencial perto de blindados aliados.',
    procedencia: 'jogo',
  },

  /* ----------------------------- Reconhecimento ----------------------------- */
  {
    id: 'drone-reconhecimento',
    nome: 'Drone de Reconhecimento',
    nomeOriginal: 'Recon Drone',
    classe: 'reconhecimento',
    tipo: 'gadget',
    descricao: 'Sobrevoa o objetivo e marca todo mundo antes de o esquadrão entrar.',
    procedencia: 'jogo',
  },
  {
    id: 'designador-laser',
    nome: 'Designador Laser',
    nomeOriginal: 'Laser Designator',
    classe: 'reconhecimento',
    tipo: 'gadget',
    descricao: 'Ilumina blindados para que os mísseis aliados travem no alvo.',
    procedencia: 'jogo',
  },
  {
    id: 'dardo-rastreador',
    nome: 'Dardo Rastreador',
    nomeOriginal: 'Tracer Dart',
    classe: 'reconhecimento',
    tipo: 'gadget',
    descricao: 'Gruda no veículo inimigo e o mantém visível para todo o time.',
    procedencia: 'jogo',
  },
  {
    id: 'isca-sniper',
    nome: 'Isca de Sniper',
    nomeOriginal: 'Sniper Decoy',
    classe: 'reconhecimento',
    tipo: 'gadget',
    descricao: 'Silhueta falsa que atrai o tiro e revela a posição de quem atirou.',
    procedencia: 'jogo',
  },
  {
    id: 'mina-antipessoal',
    nome: 'Mina Antipessoal',
    nomeOriginal: 'Anti-Personnel Mine',
    classe: 'reconhecimento',
    tipo: 'gadget',
    descricao: 'Protege o flanco enquanto você observa o objetivo pela luneta.',
    procedencia: 'jogo',
  },
  {
    id: 'carga-demolicao',
    nome: 'Carga de Demolição',
    nomeOriginal: 'Demolition Charge',
    classe: 'reconhecimento',
    tipo: 'gadget',
    descricao: 'Explosivo de detonação remota para estruturas e emboscadas.',
    procedencia: 'jogo',
  },

  /* ------------------------- Arremessáveis (todas) ------------------------- */
  {
    id: 'granada-fragmentacao',
    nome: 'Granada de Fragmentação',
    nomeOriginal: 'Frag Grenade',
    classe: 'todas',
    tipo: 'granada',
    descricao: 'Explosivo padrão: resolve cômodo fechado e grupo parado.',
    procedencia: 'jogo',
  },
  {
    id: 'granada-incendiaria',
    nome: 'Granada Incendiária',
    nomeOriginal: 'Incendiary Grenade',
    classe: 'todas',
    tipo: 'granada',
    descricao: 'Nega uma área por alguns segundos — ótima para travar corredor.',
    procedencia: 'jogo',
  },
  {
    id: 'granada-fumaca',
    nome: 'Granada de Fumaça',
    nomeOriginal: 'Smoke Grenade',
    classe: 'todas',
    tipo: 'granada',
    descricao: 'Cobre a reanimação de um aliado ou a travessia de um vão exposto.',
    procedencia: 'jogo',
  },
  {
    id: 'granada-concussao',
    nome: 'Granada de Concussão',
    nomeOriginal: 'Concussion Grenade',
    classe: 'todas',
    tipo: 'granada',
    descricao: 'Desorienta sem matar: entra na sala logo atrás dela.',
    procedencia: 'jogo',
  },
  {
    id: 'granada-atordoamento',
    nome: 'Granada de Atordoamento',
    nomeOriginal: 'Flashbang',
    classe: 'todas',
    tipo: 'granada',
    descricao: 'Cega quem estiver olhando na direção do estouro.',
    procedencia: 'jogo',
  },
  {
    id: 'coquetel-molotov',
    nome: 'Coquetel Molotov',
    nomeOriginal: 'Molotov Cocktail',
    classe: 'todas',
    tipo: 'granada',
    descricao: 'Poça de fogo imediata, útil para bloquear escada e porta.',
    procedencia: 'jogo',
  },
  {
    id: 'granada-impacto',
    nome: 'Granada de Impacto',
    nomeOriginal: 'Impact Grenade',
    classe: 'todas',
    tipo: 'granada',
    descricao: 'Detona ao tocar a superfície: sem tempo de reação para o alvo.',
    procedencia: 'jogo',
  },
];

export const GADGETS_POR_ID = new Map<string, Gadget>(GADGETS.map((g) => [g.id, g]));

export function gadgetsDaClasse(classe: IdClasse): Gadget[] {
  return GADGETS.filter((g) => g.classe === classe && g.tipo === 'gadget');
}

export function arremessaveis(): Gadget[] {
  return GADGETS.filter((g) => g.tipo === 'granada');
}
